import { DOT_STATUS_VARIANTS } from '@chghealthcare/unified-design-system'
import { DOCTOR_AVATAR_BY_FIRST_NAME } from '@/lib/doctor-avatars'

import type { ShadcnUiSlug } from './shadcn-ui-registry'
import type { PropDefinition } from './types'

const r = (
  name: string,
  type: string,
  description: string,
  defaultValue?: string,
): PropDefinition => ({ name, type, description, default: defaultValue })

/** Props forwarded to DOM / Radix / library beyond the rows above. */
const MORE: PropDefinition = r(
  '…',
  'varies',
  'Additional props are forwarded to the underlying element or primitive. See `src/components/ui/<slug>.tsx` for the full TypeScript type.',
)

const CN = r('className', 'string', 'Merged with `cn()` for layout and theme styling.')

/** Full union for PropsTable; kept in sync with `DoctorFirstName` in `doctor-avatars`. */
const DOCTOR_FIRST_NAME_PROP_TYPE = (
  Object.keys(DOCTOR_AVATAR_BY_FIRST_NAME) as (keyof typeof DOCTOR_AVATAR_BY_FIRST_NAME)[]
)
  .slice()
  .sort()
  .map((name) => `"${name}"`)
  .join(' | ')

const DOT_STATUS_VARIANT_PROP_TYPE = DOT_STATUS_VARIANTS.map((v) => `"${v}"`).join(' | ')

export const SHADCN_COMPONENT_PROPS: Record<ShadcnUiSlug, PropDefinition[]> = {
  accordion: [
    r(
      'variant',
      '"boxed" | "boxed-filled" | "divided" | "separated"',
      '`divided`: dividers only, no outer frame. `boxed`: outer border, 4px radius, light gray trigger strip. `boxed-filled`: outer border with `uds-surface-secondary` fill. `separated`: each item its own bordered, `uds-surface-secondary`-filled card with a 12px gap between items. Figma variant labels: Divided, Boxed, Boxed Filled, Separated.',
      'divided',
    ),
    r('type', '"single" | "multiple"', 'How many sections may be open at once.'),
    r('collapsible', 'boolean', 'In single mode, allow closing the open item.', 'false'),
    r('value', 'string | string[]', 'Controlled open item value(s).'),
    r('defaultValue', 'string | string[]', 'Initial open value(s) when uncontrolled.'),
    r('onValueChange', '(value: string) => void', 'Fired when the open section changes.'),
    r('AccordionItem.value', 'string', 'Required unique id for each item.'),
    CN,
    MORE,
  ],
  alert: [
    r(
      'variant',
      '"default" | "destructive" | "warning" | "success"',
      'Matches Figma `Variant`. Semantic variants tint border and copy; default keeps description secondary.',
      'default',
    ),
    r(
      'style',
      '"default" | "filled"',
      'Surface treatment. `default` is white surface + strong semantic border; `filled` is a soft accent wash (pastel-adjacent) for quieter alerts.',
      'default',
    ),
    r(
      'AlertTitle / AlertDescription',
      '—',
      'Figma text styles `Body/16/Semibold` (title) and `Body/14/Regular` (description), implemented via `Text`.',
      '—',
    ),
    r(
      'children',
      'ReactNode',
      'Optional leading `<Medallion />` or SVG, then `AlertContent` wrapping `AlertTitle` + `AlertDescription` (recommended). Title and description may still be direct children for backward compatibility.',
      '—',
    ),
    CN,
    MORE,
  ],
  'alert-dialog': [
    r('open', 'boolean', 'Controls dialog visibility.'),
    r('onOpenChange', '(open: boolean) => void', 'Visibility change callback.'),
    r(
      'AlertDialogMedia (slot)',
      'ReactNode',
      'Optional header icon via `Medallion` when `icon` is set. Default size uses red pastel; `size="sm"` / `compact` uses amber. Override with `color`.',
    ),
    r(
      'AlertDialogCopy',
      'ReactNode',
      'Wraps title + description in the default (400px) layout. Omit for compact (320px) where title and description stack directly in the header.',
    ),
    r('size (AlertDialogContent)', '"default" | "sm" | "compact"', '400px wide by default; 320px for sm/compact.'),
    r(
      'buttons (AlertDialogContent)',
      '"multiple" | "single"',
      'Matches Figma `Buttons` variant. `multiple` shows Cancel + Continue; `single` shows Continue only.',
    ),
    CN,
    MORE,
  ],
  'aspect-ratio': [
    r('ratio', 'number', 'Width / height ratio (width ÷ height, e.g. 16 / 9).'),
    r('src', 'string', 'Image URL.'),
    r('alt', 'string', 'Accessible description for the image.'),
    CN,
    MORE,
  ],
  avatar: [
    r(
      'size',
      "'xs' | 'sm' | 'default' | 'lg'",
      'Square size: 32px / 36px / 48px / 64px.',
      'default',
    ),
    r(
      'doctor',
      DOCTOR_FIRST_NAME_PROP_TYPE,
      'On `DoctorAvatar` / `DoctorAvatarImage` only: lowercase first name mapped to a portrait in `public/avatars/doctors/`.',
    ),
    r('AvatarImage.src', 'string', 'Image URL (omit on `DoctorAvatarImage`; use `doctor` instead).'),
    r('AvatarImage.alt', 'string', 'Accessible description.'),
    r('AvatarFallback.delayMs', 'number', 'Delay before showing fallback.', '600'),
    r(
      'AvatarStatus.variant',
      DOT_STATUS_VARIANT_PROP_TYPE,
      'Bottom-right `DotStatus` (always `size="medium"` / 10px). Per-size nudge from avatar corner: `xs` +1px out; `sm`/`default` −1px in; `lg` −4px in. Place `AvatarStatus` after image/fallback.',
      'green',
    ),
    r('AvatarStatus.outline', 'boolean', 'Forwarded to `DotStatus` ring treatment.', 'false'),
    r(
      'status',
      'DotStatusVariant',
      '`DoctorAvatar` only: shorthand for `AvatarStatus`; omit to hide the dot. Values match `AvatarStatus.variant` above.',
      '—',
    ),
    r('statusOutline', 'boolean', '`DoctorAvatar` only: passed to `AvatarStatus`.', 'false'),
    r(
      'AvatarCameraAction',
      'button + icon',
      '`xs`: 16×16 badge, 8px icon, +6px past corner; `sm`/`default`: 20×20 badge, 12px icon, +8px; `lg`: 24×24 badge, 16px icon, +4px. UDS gray fill, regular-weight camera icon (inverted in dark). Forwards `<button>` props; default `type="button"`, Phosphor `Camera`; override with `icon`.',
      '—',
    ),
    r(
      'cameraAction',
      'AvatarCameraActionProps',
      '`DoctorAvatar` only: spread onto `AvatarCameraAction` (omit prop to hide).',
      '—',
    ),
    CN,
    MORE,
  ],
  badge: [
    r(
      'variant',
      'string',
      'Legacy shadcn cva styles (default, secondary, destructive, outline, …) used only when `accent` is omitted. Prefer `accent` + `appearance` for UDS badges.',
      'default',
    ),
    r(
      'shape',
      "'pill' | 'rect'",
      '`pill`: fully rounded ends (`rounded-4xl`). `rect`: 2px corner radius (`rounded-[2px]`).',
      'pill',
    ),
    r(
      'size',
      "'default' | 'sm'",
      '`sm`: shorter control (`h-5`), tighter horizontal padding, same `text-xs` label as default with `leading-none`, and smaller icons (`h-2.5 w-2.5`).',
      'default',
    ),
    r(
      'accent',
      'BadgeAccent | undefined',
      'UDS accent family: transparent, neutral, red, orange, yellow, emerald, green, sky, cyan, blue, indigo, purple, fuchsia, magenta, inverse. When set, drives colors; `variant` is ignored. Figma Accent property uses matching labels (e.g. Blue, Neutral).',
    ),
    r(
      'appearance',
      "'subtle' | 'pastel' | 'outlined' | 'solid'",
      'Label-only badge treatment when `accent` is set. Subtle = transparent bg; Pastel = light fill; Outlined = border; Solid = filled. Figma Appearance: Subtle, Pastel, Outlined, Solid.',
      'solid',
    ),
    r(
      'icon',
      'ReactNode',
      'Leading/trailing icon (Phosphor, etc.); pairs with `iconPlacement`. Ignored when `asChild` is true — put `data-icon="inline-start|inline-end"` on an icon child instead.',
    ),
    r('iconPlacement', "'inline-start' | 'inline-end'", 'Side of the label for `icon`.', 'inline-start'),
    r('asChild', 'boolean', 'Merge onto child via Slot.', 'false'),
    CN,
    MORE,
  ],
  breadcrumb: [
    r(
      'size',
      '"default" | "compact"',
      'Typography: `default` is body/14; `compact` is body/12 (one step smaller). Nested under `PageHeaderNav`, Breadcrumb defaults to `compact`.',
      'default',
    ),
    r(
      'BreadcrumbSeparator.children',
      'ReactNode',
      'Optional. Default `/` with quaternary text; override for icons or other markers. Separator/ellipsis icon size follows `size`.',
    ),
    CN,
    MORE,
  ],
  branding: [
    r(
      'appearance',
      'BrandingAppearance',
      'Product or brand variant: Connect, CHG (Unified Design System SVGs + Connect-aligned tokens via data-brand), Locumsmart, Wireframe, MyWeatherby, MyCompHealth, Modio, CareerMD, myGMS, Aire, or Design System.',
      'Wireframe',
    ),
    r(
      'symbol',
      'boolean',
      'When true, renders the square mark (64×64). When false, the full wordmark (200×80).',
      'false',
    ),
    r(
      'wordmarkAlign',
      "'start' | 'center'",
      'Wordmark only: horizontal alignment of SVG inside the frame (`center` for nav / hero lockups).',
      "'start'",
    ),
    CN,
    MORE,
  ],
  button: [
    r(
      'variant',
      'enum',
      'default | outline | secondary | ghost | destructive | link. Figma Appearance: Default, Outline, Secondary, Ghost, Destructive, Link.',
      'default',
    ),
    r(
      'size',
      'enum',
      'default | 2x-sm | xs | sm | lg | icon | icon-xs | icon-sm | icon-lg. Icon-only sizes are always square: icon-xs 24, icon-sm 36, icon 44, icon-lg 52. Auto SVG glyph sizes follow Figma slots 12/16/16/20/24 — see design-language/semantics/button-icon-size.md.',
      'default',
    ),
    r(
      'children / icons',
      'ReactNode',
      'Label text plus optional leading/trailing icons (`data-icon="inline-start"` / `inline-end"`). Figma mirrors this with `Slot start` / `Slot end` (16–24px per size) toggled via `Show slot start` / `Show slot end`; wrappers are HUG, centered, 8px gap to label.',
    ),
    r('asChild', 'boolean', 'Render as child element.', 'false'),
    CN,
    MORE,
  ],
  'button-group': [
    r('orientation', '"horizontal" | "vertical"', 'Stack direction.', 'horizontal'),
    CN,
    MORE,
  ],
  calendar: [
    r('mode', '"single" | "range" | "multiple"', 'Selection mode.'),
    r('selected / defaultSelected', 'Date | DateRange | Date[]', 'Current or initial selection.'),
    r('onSelect', '(date) => void', 'Selection change handler.'),
    r('disabled', 'Matcher | Matcher[]', 'Dates that cannot be selected.'),
    r('locale', 'Locale', 'date-fns locale for labels.'),
    CN,
    MORE,
  ],
  card: [
    r('size', '"default" | "sm"', 'Card size. "sm" renders the Compact variant (Figma Size=Compact).'),
    r(
      'orientation',
      '"vertical" | "horizontal"',
      '"horizontal" moves CardFooter beside CardContent instead of below it (Figma Appearance=Horizontal). CardImage always stays full-width on top. Matches the official Figma Card’s Show Image toggle.',
      'vertical',
    ),
    r(
      'children',
      'ReactNode',
      'Three optional slots: CardImage (images only), CardContent (any children), CardFooter (buttons only). Naked Cards (no slot children) auto-apply 16px padding so content is not flush to the border.',
    ),
    CN,
    MORE,
  ],
  chart: [
    r('ChartContainer.config', 'ChartConfig', 'Series labels, colors, and theme mapping.'),
    r('ChartContainer.initialDimension', '{ width; height }', 'SSR / first paint size.'),
    r(
      'Bar.radius (stacked)',
      'number | [tl, tr, br, bl]',
      'Stacked bars: touching ends must be 0. Vertical two-stack example: bottom `[0,0,4,4]`, top `[4,4,0,0]`. Do not use `radius={4}` on every stacked series.',
    ),
    CN,
    MORE,
  ],
  'check-list': [
    r('CheckListControl.id', 'string', 'Unique id linking checkbox and label.'),
    r('CheckListControl.label', 'ReactNode', 'Primary task label.'),
    r('CheckListControl.description', 'ReactNode', 'Optional secondary helper text.'),
    r('CheckListControl.checked', 'boolean', 'Controlled checked state.'),
    r('CheckListControl.onCheckedChange', '(checked) => void', 'Checkbox state change callback.'),
    CN,
    MORE,
  ],
  checkbox: [
    r('checked', 'boolean | "indeterminate"', 'Controlled state.'),
    r('defaultChecked', 'boolean', 'Initial state when uncontrolled.'),
    r('onCheckedChange', '(checked: boolean) => void', 'Change callback.'),
    r('disabled', 'boolean', 'Non-interactive.', 'false'),
    r('required', 'boolean', 'Participates in form validation.', 'false'),
    r('name', 'string', 'Form field name.'),
    r('value', 'string', 'Submitted value when checked.'),
    CN,
    MORE,
  ],
  collapsible: [
    r('open', 'boolean', 'Controlled open state.'),
    r('onOpenChange', '(open: boolean) => void', 'Open state callback.'),
    r('defaultOpen', 'boolean', 'Initial open when uncontrolled.', 'false'),
    r('variant', '"boxed" | "divided"', 'Chrome aligned with Accordion.', '"divided"'),
    r(
      'CollapsibleTrigger.children',
      'ReactNode',
      'Trigger label/content. A caret icon is rendered automatically after the children (right-aligned) and flips on expand, matching AccordionTrigger — do not add your own caret.',
    ),
    r('CollapsibleContent.contentClassName', 'string', 'Classes merged onto the inner panel (default `px-4 pt-0 pb-3`).', '—'),
    CN,
    MORE,
  ],
  combobox: [
    r('items', 'readonly any[]', 'Source list for filtering. Pair with `ComboboxList` render-prop children so Base UI maps `filteredItems` into items.', '—'),
    r('itemToStringLabel', '(value) => string', 'Maps each item value to the filter/display string when labels differ from values (e.g. value `next` → label `Next.js`). Omit when label === value.', '—'),
    r('ComboboxList.children', '(item) => ReactNode', 'Render-prop (shadcn pattern). Required for type-to-filter; static `ComboboxItem` children are not filtered.', '—'),
    r('value / defaultValue', 'string', 'Selected option value.'),
    r('onValueChange', '(value: string) => void', 'Selection callback.'),
    r('disabled', 'boolean', 'Disable the control.', 'false'),
    r('ComboboxInput.inputSize', '"default" | "sm"', 'Trigger height and typography. Figma `Size=Default` → `default` (44px); `Size=Small` → `sm` (36px).', 'default'),
    r('ComboboxInput.placeholder', 'string', 'Placeholder when no value is selected.', '"Select an option"'),
    CN,
    MORE,
  ],
  command: [
    r('value / defaultValue', 'string', 'Active item value (cmdk).'),
    r('onValueChange', '(value: string) => void', 'Selection change.'),
    r('filter', '(value, search) => number', 'Custom filter function.'),
    r('shouldFilter', 'boolean', 'Enable built-in filtering.', 'true'),
    r('loop', 'boolean', 'Keyboard wrap at ends.', 'false'),
    CN,
    MORE,
  ],
  'context-menu': [
    r('open / onOpenChange', 'boolean / fn', 'Controlled menu visibility.'),
    r('modal', 'boolean', 'Modal focus trap behavior.', 'true'),
    CN,
    MORE,
  ],
  'description-list': [
    r('DescriptionRow', 'layout helper', 'Wrap each term/detail pair with a semantic grouping wrapper.'),
    r('DescriptionTerm', 'dt', 'Term label cell.'),
    r('DescriptionDetail', 'dd', 'Value/detail cell.'),
    CN,
    MORE,
  ],
  dialog: [
    r('open', 'boolean', 'Controlled visibility.'),
    r('onOpenChange', '(open: boolean) => void', 'Visibility callback.'),
    r('defaultOpen', 'boolean', 'Initial open.', 'false'),
    r('size (DialogContent)', '"sm" | "md" | "lg" | "xl" | "2xl"', 'Panel max width: 384 / 448 / 512 / 576 / 672px. Default md (448px).'),
    r('showCloseButton (DialogContent)', 'boolean', 'Top-right dismiss control.', 'true'),
    r('DialogMain', 'layout helper', 'Wraps header + DialogBody with Figma main padding (p-16, gap-16).'),
    r('DialogBody', 'slot', 'Body region below the header (Figma Content2).'),
    r('DialogDescription', 'optional', 'Omit when Figma `description` is false.'),
    CN,
    MORE,
  ],
  direction: [
    r('dir / direction', '"ltr" | "rtl"', 'Document direction for descendants.'),
    MORE,
  ],
  'dot-status': [
    r(
      'variant',
      DOT_STATUS_VARIANT_PROP_TYPE,
      'Fill from the UDS accent scale; `neutral` and `inverse` are semantic; `celery` uses the emerald accent (yellow-green).',
      'green',
    ),
    r(
      'size',
      '"small" | "medium" | "large"',
      'Dot size: 8px / 10px / 12px (`size-2` / `size-2.5` / `size-3`) — medium and large are tighter vs small than the prior 12/16 scale.',
      'medium',
    ),
    r('outline', 'boolean', 'Adds a 2px `--uds-border-primary` border around the dot.', 'false'),
    CN,
    MORE,
  ],
  drawer: [
    r('open', 'boolean', 'Drawer visibility.'),
    r('onOpenChange', '(open: boolean) => void', 'Visibility callback.'),
    r('dismissible', 'boolean', 'Allow swipe / overlay close.', 'true'),
    r(
      'DrawerContent',
      '—',
      'Corner radius always 0. Left/right width clamped 320–600px (`min-w-[320px] max-w-[600px]`). Full-height flex column; compose Header / Body / Footer.',
    ),
    r(
      'DrawerBody',
      'slot',
      'Required scrollable middle between DrawerHeader and DrawerFooter (`min-h-0 flex-1 overflow-y-auto`). Side footers use a horizontal action row.',
    ),
    CN,
    MORE,
  ],
  'dropdown-menu': [
    r('open / onOpenChange', 'boolean / fn', 'Menu visibility.'),
    r('modal', 'boolean', 'Modal behavior.', 'true'),
    CN,
    MORE,
  ],
  'date-input': [
    r('inputSize', "'default' | 'sm'", 'Field height and typography. Figma `Size=Default` → `default` (44px); `Size=Compact` → `sm` (36px).', 'default'),
    r('type', '"text"', 'Preset to a text field with a single-date calendar picker.', 'text'),
    r('placeholder', 'string', 'Defaults to `mm/dd/yyyy`.'),
    r('date', 'Date | undefined', 'Controlled selected date.'),
    r('defaultDate', 'Date | undefined', 'Initial selected date (uncontrolled mode).'),
    r(
      'onDateChange',
      '(date: Date | undefined) => void',
      'Fires when the date changes from the calendar or from typing digits only (auto-formatted as `mm/dd/yyyy`, committed on blur; invalid input reverts).',
    ),
    r(
      'yearSelection',
      "'grid' | 'caption'",
      'Default `grid`: caption shows month and year each with a caret; open a 12-cell month table (arrows change year) or a 12-year table (arrows page years). In month/year grids, pick a value to return to days. `caption` uses DayPicker `captionLayout` (e.g. `dropdown-years`) instead.',
      'grid',
    ),
    r(
      'captionLayout',
      "'label' | 'dropdown' | 'dropdown-months' | 'dropdown-years'",
      'When `yearSelection` is `caption`, forwarded to `Calendar` / DayPicker. Ignored when `yearSelection` is `grid`.',
      'dropdown-years',
    ),
    r('startMonth', 'Date', 'First month / minimum year in navigation bounds.', '100 years before current year'),
    r('endMonth', 'Date', 'Last month / maximum year in navigation bounds.', '50 years after current year'),
    r('inputMode', 'string', 'Hints numeric keypad for date entry formatting.', 'numeric'),
    r('autoComplete', 'string', 'Date autocomplete hint for browser autofill.', 'bday'),
    CN,
    MORE,
  ],
  'date-range-input': [
    r('type', '"text"', 'Preset to a text field with a range-calendar picker.', 'text'),
    r('separator', 'string', 'Display separator between start/end dates.', '" – "'),
    r('placeholder', 'string', 'Defaults to `mm/dd/yyyy – mm/dd/yyyy`.'),
    r('range', 'DateRange | undefined', 'Controlled selected date range.'),
    r('defaultRange', 'DateRange | undefined', 'Initial selected date range (uncontrolled mode).'),
    r(
      'onRangeChange',
      '(range: DateRange | undefined) => void',
      'Fires when the range changes from the calendar or from typing digits only (two `mm/dd/yyyy` segments auto-formatted; `separator` is inserted after the first 8 digits; committed on blur; invalid input reverts).',
    ),
    r(
      'yearSelection',
      "'grid' | 'caption'",
      'Default `caption`: DayPicker label captions (no month/year `<select>`; no month/year grid). Use `grid` for the same caption/grid UX as `DateInput`.',
      'caption',
    ),
    r(
      'captionLayout',
      "'label' | 'dropdown' | 'dropdown-months' | 'dropdown-years'",
      'When `yearSelection` is `caption`, forwarded to `Calendar` / DayPicker. Default `label` (text caption + nav arrows only). Ignored for `grid`.',
      'label',
    ),
    r('startMonth', 'Date', 'First month / minimum year in navigation bounds.', '100 years before current year'),
    r('endMonth', 'Date', 'Last month / maximum year in navigation bounds.', '50 years after current year'),
    r('inputMode', 'string', 'Hints numeric keypad for date entry formatting.', 'numeric'),
    CN,
    MORE,
  ],
  empty: [
    r(
      'EmptyMedia (slot)',
      'ReactNode',
      'Icon or illustration; chrome comes from theme: `src/styles/uds-chrome-media.css` via `[data-slot="empty-icon"]`.',
    ),
    CN,
    r('children', 'ReactNode', 'Title, description, media, actions.'),
    MORE,
  ],
  'event-card': [
    r(
      'color',
      '"sky" | "emerald" | "red" | "amber" | "aqua" | "blue" | "cyan" | "fuchsia" | "green" | "indigo" | "lime" | "magenta" | "orange" | "purple" | "rose" | "violet" | "yellow"',
      'Left-border and background accent color. Full UDS accent palette (17 hues).',
      '"sky"',
    ),
    r('title', 'ReactNode', 'Bold heading line (location or vendor name).'),
    r(
      'type',
      'ReactNode',
      'Right-aligned slot — an icon, a label, a badge, or any combination of components. Compose with EventCardTypeLabel for the icon + label pattern.',
    ),
    r(
      'children',
      'ReactNode',
      'Detail rows under the title — compose with EventCardDetail / EventCardRoute or plain text.',
    ),
    CN,
    MORE,
  ],
  field: [
    r('FieldSet.name', 'string', 'Group name for nested controls.'),
    r('FieldLegend', 'ReactNode', 'Accessible group label.'),
    r('FieldLabel.htmlFor', 'string', 'Associates label with control id.'),
    CN,
    MORE,
  ],
  'file-upload': [
    r('onFileSelect', '(files: File[]) => void', 'Called when files are selected via click or drag/drop.'),
    r(
      'size',
      '"default" | "small" | "xs"',
      'Dropzone scale; `xs` is a single short row (xs medallion, 48px min-height, title - helper on one line when defaults apply).',
      'default',
    ),
    r('multiple', 'boolean', 'Allow selecting multiple files from chooser and drop.', 'false'),
    r('accept', 'string', 'Native file input accept filter (e.g. `.pdf,image/*`).'),
    r('title', 'ReactNode', 'Primary dropzone copy — Figma `title`; renders as Instruction (default/small) or Title (xs).'),
    r('desc', 'ReactNode', 'Secondary dropzone copy — Figma `desc`; renders as Helper (default/small) or Desc (xs).'),
    r('descClassName', 'string', 'Optional classes merged onto the desc/helper text element.'),
    CN,
    MORE,
  ],
  'file-upload-cards': [
    r('items / defaultItems', 'FileUploadCardItem[]', 'Controlled or initial card models for rich status/progress rendering.'),
    r('files / defaultFiles', 'File[]', 'Simple file-only mode; files are mapped into default card items.'),
    r('onItemsChange', '(items: FileUploadCardItem[]) => void', 'Called whenever card items are added, removed, or replaced.'),
    r('onFilesChange', '(files: File[]) => void', 'Called with the `File` subset whenever card items change.'),
    r('FileUploadCardItem.status', '"idle" | "uploading" | "success" | "error" | "disabled"', 'Per-card state token used for status badge and interaction behavior.', '"idle"'),
    r('FileUploadCardItem.progress', 'number', 'Upload progress percentage shown when status is `uploading`.', '0'),
    r('FileUploadCardItem.errorMessage', 'string', 'Inline error text shown when status is `error`.'),
    r('onRetry / onView / onDownload', '(item) => void', 'Optional action callbacks for retry/view/download controls on each card.'),
    r('desc', 'ReactNode', 'Secondary dropzone copy passed to the embedded FileUpload.', '"PDF, DOCX, PNG up to 10MB each"'),
    r('multiple', 'boolean', 'Allows selecting multiple files per browse/drop action.', 'true'),
    r(
      'density',
      "'default' | 'compact'",
      '`compact`: tighter list spacing, smaller Medallion and actions, `Badge size="sm"`, and defaults the dropzone to `size="xs"` unless you pass `size` explicitly.',
      'default',
    ),
    r(
      'FileUploadCardItem + data-slot',
      '—',
      'Card row mirrors Figma layers: `medallion` (Blue pastel + File/Image icon), `file-name`, Pill pastel `Badge`, `metadata`, `progress` (Progress bar only, no label), `error-message`, `actions` SLOT (X; retry+X on error; hidden when disabled).',
    ),
    CN,
    MORE,
  ],
  footer: [
    r('copyright', 'string', 'Copyright text displayed on the left. Defaults to current-year CHG Management notice.'),
    r('links', 'FooterLink[]', 'When non-empty, selects Links=On: copyright (flex-1) plus default link nav in the Content slot.'),
    r('children', 'ReactNode', 'Content slot (Links=On only). Replaces the default link nav; copyright still renders on the left.'),
    CN,
    MORE,
  ],
  header: [
    r('showMenuToggle', 'boolean', 'Show the menu collapse/expand control (AppShell wires this). Always visible — does not hide when the rail collapses.', 'false'),
    r('menuExpanded', 'boolean', 'Controlled menu expanded / drawer-open state for the toggle aria-expanded.', 'true'),
    r('onMenuToggle', '() => void', 'Called when the menu toggle is activated.'),
    r('brand', 'UdsBrandId', 'Brand id for Header wordmark artwork.', 'chg'),
    r('headerVariant', "'brand' | 'title'", 'Wordmark (default) or plain title text.', 'brand'),
    r('headerTitle', 'string', 'Product/app name when headerVariant is title.'),
    r('children', 'ReactNode', 'Custom content that replaces the default SearchInput only (not brand/toggle).'),
    r(
      'trailing',
      'ReactNode',
      'Right-aligned trailing slot for utility actions (icon buttons, avatar, dropdowns). Not recommended: an additional SearchInput — Header already provides leading search via searchProps / default SearchInput.',
    ),
    r('searchProps', 'SearchInputProps', 'Props forwarded to the default SearchInput. Ignored when `children` is provided or `hideSearch` is true. Below lg, search collapses to an icon that expands this field.'),
    r(
      'hideSearch',
      'boolean',
      'When true, omit the default SearchInput. Ignored when `children` is provided. AppShell also exposes `hideSearch` / `headerLeading`. Does not remove brand/toggle.',
      'false',
    ),
    CN,
    MORE,
  ],
  input: [
    r('inputSize', "'default' | 'sm'", 'Field height and typography. Figma `Size=Default` → `default` (44px); `Size=Compact` → `sm` (36px).', 'default'),
    r('type', 'string', 'HTML input type.', 'text'),
    r('value / defaultValue', 'string', 'Controlled / initial value.'),
    r('onChange', 'ChangeEventHandler', 'Input change.'),
    r('placeholder', 'string', 'Hint text.'),
    r('disabled', 'boolean', 'Non-editable.', 'false'),
    r('readOnly', 'boolean', 'Read-only field.', 'false'),
    r('required', 'boolean', 'Required for forms.', 'false'),
    r('name / id', 'string', 'Form identity.'),
    CN,
    MORE,
  ],
  'input-group': [
    CN,
    r('children', 'ReactNode', 'Addon + input composition.'),
    MORE,
  ],
  'input-otp': [
    r('maxLength', 'number', 'Number of OTP cells.', '6'),
    r('value / onChange', 'string / fn', 'Controlled value.'),
    r('disabled', 'boolean', 'Disables entry; root opacity 50% (matches Figma State=Disabled).', 'false'),
    r(
      'InputOTPGroup.inputSize',
      '"default" | "sm"',
      '`default` — 64×70 slots, Display/48/Medium (Figma Size=Default). `sm` — 44×48 compact, Display/36/Medium (Figma Size=Compact).',
      'default',
    ),
    r(
      'InputOTPGroup.responsive',
      'boolean',
      'When true (default), `inputSize="default"` auto-compresses below 768px to match Size=Compact.',
      'true',
    ),
    r(
      'InputOTPSlot.index',
      'number',
      'Zero-based slot index passed to `input-otp` context.',
    ),
    r(
      'InputOTPSeparator',
      'component',
      'Minus divider — place after slot index 2. Icon 32px (default) or 20px (compact).',
    ),
    r(
      'aria-invalid',
      'boolean',
      'On the group or input: active slot uses destructive border + ring (Figma State=Error).',
    ),
    CN,
    MORE,
  ],
  item: [
    r('appearance', "'list' | 'box'", 'List is flush (no radius); Box uses uds/radius/4.', 'box'),
    r('variant', "'default' | 'outline' | 'muted'", 'Maps to Figma State axis.', 'default'),
    r('size', "'default' | 'sm'", 'Compact in Figma → sm (smaller title/description type).', 'default'),
    CN,
    MORE,
  ],
  kbd: [
    CN,
    r('children', 'ReactNode', 'Key cap label(s).'),
    MORE,
  ],
  label: [
    r('htmlFor', 'string', 'Target control id.'),
    r(
      'RadioGroupLabel',
      'typeof Label',
      'Use `RadioGroupLabel` from `@chghealthcare/unified-design-system`: UDS body-16 regular for `RadioGroupItem` captions.',
    ),
    CN,
    MORE,
  ],
  layout: [
    r(
      'direction',
      '"row" | "col" | "row-reverse" | "col-reverse" | CSS flex-direction',
      '`col` / `col-reverse` map to `column` / `column-reverse`. Any other string is forwarded as `flexDirection`.',
      'row',
    ),
    r('alignItems', 'CSS align-items', 'Flex cross-axis alignment (e.g. `center`, `stretch`, `flex-start`).'),
    r('justifyContent', 'CSS justify-content', 'Flex main-axis distribution (e.g. `space-between`, `center`).'),
    r(
      'gap',
      'number | string',
      'Number: theme spacing index (`n × 0.25rem`, same as Tailwind `gap-*`). String: raw CSS `gap` value.',
    ),
    r(
      'wrap',
      'boolean | "nowrap" | "wrap" | "wrap-reverse"',
      '`true` / `false` map to `wrap` / `nowrap`. Strings are passed through as CSS `flex-wrap`.',
    ),
    r(
      'as',
      'keyof JSX.IntrinsicElements',
      'Intrinsic HTML tag for the flex root (e.g. `div`, `ul`, `section`).',
      'div',
    ),
    CN,
    MORE,
  ],
  link: [
    r('appearance', "'primary' | 'secondary'", 'Link color pair. Figma Appearance=Primary|Secondary.', 'primary'),
    r('external', 'boolean', 'Applies external link defaults (`target`, `rel`) and icon.', 'false'),
    r('showExternalIcon', 'boolean', 'Shows trailing external-link icon when `external` is true.', 'true'),
    r('href', 'string', 'Destination URL.'),
    CN,
    MORE,
  ],
  'main-content': [
    r(
      'containment',
      '"edge" | "fixed"',
      'Edge (default): full width on surface-secondary. Fixed: outer max 1280px, surface-primary, border-right only, no L/R padding, no min-height; left-aligned inner max 1000px.',
      'edge',
    ),
    r(
      'appearance',
      '"default" | "expanded"',
      'Padding density. Fixed inner: `default` = 24px, `expanded` = 48px. Edge: `default` has no built-in padding (recommend 24px via className); `expanded` applies 48px on the root.',
      'default',
    ),
    r(
      'MainStack.appearance',
      '"default" | "expanded"',
      'First-level section gap under PageHeader: `default` = 24px, `expanded` = 72px. Pair with expanded PageHeader / MainContent.',
      'default',
    ),
    CN,
    MORE,
  ],
  medallion: [
    r('color', 'MedallionColor', 'UDS accent/neutral key (`MEDALLION_COLORS`).'),
    r(
      'tone',
      `'pastel' | 'solid'`,
      '`pastel` — `MEDALLION_PASTEL_PALETTE` (tinted surface + deeper icon; inverts in dark). `solid` — `MEDALLION_SOLID_PALETTE` (`500` ramp fill + white icon).',
      'pastel',
    ),
    r('icon', 'ReactNode', 'Centered glyph (Phosphor recommended).'),
    r(
      'size',
      `'xs' | 'sm' | 'default' | 'lg' | 'xl'`,
      'Container and icon scale. Prefer **lg** (default) for page/section identity; use smaller sizes only in dense rows or composed chrome (AlertDialog, file cards).',
      'lg',
    ),
    r(
      'shape',
      `'circle' | 'square' | 'rounded'`,
      '`rounded` uses a 12px corner radius.',
      'circle',
    ),
    CN,
    MORE,
  ],
  menubar: [
    r('value / defaultValue', 'string', 'Active submenu value.'),
    r('onValueChange', '(value: string) => void', 'Submenu change.'),
    CN,
    MORE,
  ],
  'micro-calendar': [
    r('value', 'Date', 'Selected day (highlight).'),
    r('today', 'Date', 'Optional stand-in for the real current day (today styling and collapsed-week row).'),
    r('month', 'Date', 'Month shown (first of month); syncs from props when the reference month changes.'),
    r('onMonthChange', '(month: Date) => void', 'Optional callback when the displayed month changes from navigation.'),
    r('onDateSelect', '(date: Date) => void', 'Called when a selectable day is activated.'),
    r('unavailableDates', 'Date[]', 'Days shown as unavailable (not selectable).', '[]'),
    r(
      'dateData',
      'Record<string, MicroCalendarDateData>',
      'Per-day flags keyed by local `YYYY-MM-DD`; values may include `travel` and `onAssignment` for markers.',
      '{}',
    ),
    r('defaultExpanded', 'boolean', 'Whether the grid starts expanded or as a single-week strip.', 'true'),
    r('showLegend', 'boolean', 'Show the legend row when expanded.', 'true'),
    r('showExpandCollapse', 'boolean', 'Show the bottom caret toggle.', 'true'),
    r('MicroCalendarTile — date', 'Date', 'Single-day chip: calendar date to display.', 'new Date()'),
    r('MicroCalendarTile — locale', 'string', 'Locale for weekday and month abbreviations on the tile.', 'en-US'),
    CN,
    MORE,
  ],
  'native-select': [
    r('inputSize', '"default" | "sm"', 'Height and typography; matches Input.', 'default'),
    r('value / defaultValue', 'string', 'Selected option.'),
    r('onChange', 'ChangeEventHandler', 'Change callback.'),
    r('disabled', 'boolean', 'Disable select.', 'false'),
    r('required', 'boolean', 'Form required.', 'false'),
    r('name', 'string', 'Form name.'),
    CN,
    MORE,
  ],
  'navigation-menu': [
    r('value / defaultValue', 'string', 'Active item.'),
    r('onValueChange', '(value: string) => void', 'Selection callback.'),
    r('delayDuration', 'number', 'Hover open delay (ms).'),
    CN,
    MORE,
  ],
  'number-input': [
    r('type', '"number"', 'Preset to numeric input type.', 'number'),
    r('inputMode', 'string', 'Hints decimal keypad on mobile devices.', 'decimal'),
    r('step', 'number | string', 'Numeric step increment for controls and validation.', 'any'),
    CN,
    MORE,
  ],
  'page-header': [
    r(
      'layout',
      '"inline" | "block"',
      'Inline (default): inside padded MainContent; ≤24px to first content via margin-bottom (do not stack parent gap). Block: outside padded content, edge-to-edge with AppShell.Main.',
      'inline',
    ),
    r(
      'appearance',
      '"default" | "expanded"',
      'Padding density for `layout="block"`: `default` = 24px, `expanded` = 48px. Legacy `appearance="inline"|"block"` still maps to `layout`.',
      'default',
    ),
    r(
      'actionsPlacement',
      '"trailing" | "below"',
      'Where `PageHeaderActions` sit: `trailing` (default) beside the title stack; `below` under the description with 24px gap.',
      'trailing',
    ),
    r('PageHeaderTitle', 'ReactNode', 'Required page title (heading/28/semibold, h1) — largest headline on the page; keep SectionHeader / h2 at body/20/semibold (recommended).'),
    r(
      'PageHeaderNav',
      'ReactNode',
      'Optional back control + breadcrumb row. Nested `Breadcrumb` defaults to `size="compact"` (body/12).',
    ),
    r('PageHeaderEyebrow', 'ReactNode', 'Optional overline (body/12/tertiary).'),
    r('PageHeaderDescription', 'ReactNode', 'Optional supporting copy (body/14/tertiary, 0px below title, max-width 720px).'),
    r(
      'PageHeaderActions',
      'ReactNode',
      'Page actions: exactly one primary Button, default size; if more than three buttons, add DotsThree overflow last on the right with weight="bold". Gap ≥12px. Not for SearchInput or Badge (prefer status/count near the title). Placement follows `actionsPlacement`.',
    ),
    r(
      'PageHeaderBody',
      'ReactNode',
      'Layout for content + optional actions — row when `actionsPlacement="trailing"`, stacked (24px gap) when `below`.',
    ),
    r('PageHeaderContent', 'ReactNode', 'Title stack wrapper (eyebrow / title / description at 0px gaps).'),
    CN,
    MORE,
  ],
  pagination: [
    CN,
    r('children', 'ReactNode', 'PaginationItem / Link composition.'),
    MORE,
  ],
  'password-input': [
    r('type', '"password" | "text"', 'Toggles between masked and visible states via the eye button.', '"password"'),
    r('visible', 'boolean | undefined', 'Controlled visibility state (text when true).'),
    r('defaultVisible', 'boolean', 'Initial visibility in uncontrolled mode.', 'false'),
    r('onVisibleChange', '(visible: boolean) => void', 'Fires when the eye toggle is pressed.'),
    r('autoComplete', 'string', 'Password manager and browser autofill hint.', 'current-password'),
    CN,
    MORE,
  ],
  'phone-input': [
    r('type', '"tel"', 'Preset to telephone input type.', 'tel'),
    r('value / defaultValue', 'string | number', 'Raw digits or formatted phone string. Component normalizes to digits and re-formats on render.'),
    r('maxDigits', 'number', 'Maximum number of numeric digits kept from input.', '10'),
    r('onValueChange', '(digits: string, formattedValue: string) => void', 'Fires whenever digits change after input sanitation and formatting.'),
    r('onChange', 'ChangeEventHandler', 'Called after formatting; event currentTarget value is formatted text.'),
    r('inputMode', 'string', 'Hints phone keypad on mobile devices; non-digit key presses are blocked.', 'tel'),
    r('autoComplete', 'string', 'Telephone autofill hint.', 'tel'),
    CN,
    MORE,
  ],
  'pill-toggle': [
    r('pressed / defaultPressed', 'boolean', 'Controlled/uncontrolled selected state (Radix Toggle).'),
    r('onPressedChange', '(pressed: boolean) => void', 'Fires when the pill is toggled.'),
    r('disabled', 'boolean', 'Disables the control.', 'false'),
    CN,
    MORE,
  ],
  popover: [
    r(
      'trigger',
      '"click" | "hover"',
      '"click" renders Radix Popover (keyboard/click, supports `modal`); "hover" renders Radix HoverCard (hover/focus-in, supports `openDelay`/`closeDelay`).',
      '"click"',
    ),
    r('open / onOpenChange', 'boolean / fn', 'Popover visibility.'),
    r('modal', 'boolean', 'Modal focus behavior. Only applies when `trigger="click"`.', 'false'),
    r('openDelay / closeDelay', 'number', 'Hover timing (ms). Only applies when `trigger="hover"`.', '700 / 300'),
    CN,
    MORE,
  ],
  progress: [
    r('value', 'number | null', '0–100 completion; null for indeterminate.'),
    r('max', 'number', 'Maximum value.', '100'),
    CN,
    MORE,
  ],
  'progress-circles': [
    r('ProgressCircle.value', 'number', 'Progress percentage from 0 to 100.'),
    r('ProgressCircle.size', 'number', 'Circle diameter in px.', '72'),
    r('ProgressCircle.strokeWidth', 'number', 'Stroke width in px.', '8'),
    r('ProgressCircle.label', 'ReactNode', 'Custom label below the circle.'),
    CN,
    MORE,
  ],
  'radio-group': [
    r('value / defaultValue', 'string', 'Selected item value.'),
    r('onValueChange', '(value: string) => void', 'Change callback.'),
    r('disabled', 'boolean', 'Disable entire group.', 'false'),
    r('name', 'string', 'Form name.'),
    r('orientation', '"horizontal" | "vertical"', 'Layout.', 'vertical'),
    CN,
    MORE,
  ],
  resizable: [
    r('orientation', '"horizontal" | "vertical"', 'Resize axis.', 'horizontal'),
    r('Panel.defaultSize', 'number', 'Initial size percentage.'),
    r('Panel.minSize / maxSize', 'number', 'Size constraints.'),
    CN,
    MORE,
  ],
  'scroll-area': [
    r('type', '"auto" | "always" | "scroll" | "hover"', 'Scrollbar visibility.', 'hover'),
    r('scrollHideDelay', 'number', 'Delay before hiding (ms).'),
    CN,
    MORE,
  ],
  filterbar: [
    r('Filterbar', 'ReactNode', 'Root module (column). Compose toolbar + optional facets row.'),
    r('FilterbarToolbar', 'ReactNode', 'Top row: search cluster + trailing actions.'),
    r('FilterbarSearch', 'ReactNode', 'Left cluster for SearchInput + filter/sort controls. Search field defaults to 500px wide.'),
    r(
      'FilterbarFilters',
      'ReactNode',
      'Icon-only Buttons immediately after SearchInput (left-aligned, gap ≥12px). Use size="icon" (default height) with aria-label — not labeled text or sm.',
    ),
    r(
      'FilterbarActions',
      'ReactNode',
      'Trailing actions: exactly one primary Button, default size; if more than three buttons, add DotsThree overflow last on the right with weight="bold". Gap ≥12px.',
    ),
    r(
      'FilterbarFacets',
      'ReactNode',
      'Open slot for applied filters — pass soft Buttons (`variant="secondary"`) or any facet content (gap ≥12px).',
    ),
    r(
      'FilterbarFacet',
      'ReactNode',
      'Optional soft (`secondary`) dismissible facet Button helper for use inside FilterbarFacets.',
    ),
    r('FilterbarFacet.onRemove', '() => void', 'Called when the facet chip is activated.'),
    CN,
    MORE,
  ],
  'search-input': [
    r(
      'Usage (listview)',
      '—',
      'Inside AppShell listview: wrap with 4px padding on all sides (`p-[length:var(--uds-spacing-4)]`) and border-b. See listview-drives-main.',
    ),
    r(
      'surface',
      '"primary" | "secondary"',
      'Field fill for contrast: `primary` (white) on gray parents; `secondary` (gray, default) on white parents. In Filterbar on edge Main use `primary`.',
      'secondary',
    ),
    r('variant', '"default" | "shortcut"', '`shortcut`: show a keyboard hint before the search icon.', 'default'),
    r('shortcut', 'ReactNode', 'Custom hint when `variant` is `shortcut` (default: ⌘ + K).'),
    r('ariaKeyShortcuts', 'string', 'Optional `aria-keyshortcuts` override when `variant` is `shortcut`.'),
    r('type', '"search"', 'Preset to browser search field behavior.', 'search'),
    r('submitButtonType', '"submit" | "button" | "reset"', 'Type for the trailing magnifying-glass action button.', 'submit'),
    r('submitButtonAriaLabel', 'string', 'Accessible label for the icon submit button.', 'Submit search'),
    r('onSubmitButtonClick', 'MouseEventHandler<HTMLButtonElement>', 'Called when the trailing icon button is pressed.'),
    r('hideSubmitButton', 'boolean', 'Hides the trailing icon button and removes extra right padding.', 'false'),
    r('autoComplete', 'string', 'Disables aggressive autofill in query-style fields.', 'off'),
    CN,
    MORE,
  ],
  select: [
    r('SelectTrigger.inputSize', '"default" | "sm"', 'Trigger height and typography; matches Input.', 'default'),
    r('SelectTrigger.autofilled', 'boolean', 'Shows the same tint + sparkle icon as autofilled inputs. No real <input> backs this trigger, so it must be set explicitly rather than detected.', 'false'),
    r('value / defaultValue', 'string', 'Selected value.'),
    r('onValueChange', '(value: string) => void', 'Change callback.'),
    r('open / onOpenChange', 'boolean / fn', 'Dropdown visibility.'),
    r('disabled', 'boolean', 'Disable control.', 'false'),
    r('required', 'boolean', 'Form validation.', 'false'),
    r('name', 'string', 'Form name.'),
    r(
      'SelectContent.searchable',
      'boolean',
      'When true, shows a search field in the dropdown and filters options by label (`textValue` or string children). Off by default.',
      'false',
    ),
    r('SelectContent.searchPlaceholder', 'string', 'Visible hint text in the search field when `searchable`.', 'Search…'),
    r(
      'SelectContent.searchAriaLabel',
      'string',
      'Accessible name for the filter field (required for WCAG; do not rely on `placeholder` alone).',
      'Filter options',
    ),
    r(
      'SelectContent.searchAutoFocus',
      'boolean',
      'When `searchable`, focuses the search input after the menu opens.',
      'true',
    ),
    r(
      'SelectContent.searchFilter',
      '(query, label, itemValue) => boolean',
      'Optional custom filter when `searchable`; default is case-insensitive substring on `label`.',
      '—',
    ),
    CN,
    MORE,
  ],
  separator: [
    r(
      'variant',
      '"default" | "label" | "band"',
      '`default`: Radix line. `label`: horizontal rule with a bordered pill (`bg-background`) and optional `labelAlign`. `band`: 8px UDS neutral strip with top/bottom `uds-border-secondary` rules.',
      'default',
    ),
    r('orientation', '"horizontal" | "vertical"', 'Divider axis (`default` variant only).', 'horizontal'),
    r('decorative', 'boolean', 'Presentational only (no semantics).', 'true'),
    r('label', 'ReactNode', 'Text or node inside the pill when `variant` is `label`.', '—'),
    r('labelAlign', '"left" | "center" | "right"', 'Pill placement when `variant` is `label`.', 'center'),
    CN,
    MORE,
  ],
  'section-header': [
    r(
      'SectionHeaderTitle',
      'ReactNode',
      'Primary heading (Text body/20/semibold, lineHeight="tight", as h2 — recommended). Stay below PageHeaderTitle (heading/28).',
    ),
    r(
      'SectionHeaderDescription',
      'ReactNode',
      'Supporting copy (Text body/16/regular, lineHeight="loose", appearance="secondary" / text-secondary, 0px gap below title).',
    ),
    r(
      'SectionHeaderActions',
      'ReactNode',
      'Open trailing slot for any actions (buttons, menus, toggles, links). Vertically centered; ≥12px gap between children.',
    ),
    CN,
    MORE,
  ],
  sheet: [
    r('open', 'boolean', 'Sheet visibility.'),
    r('onOpenChange', '(open: boolean) => void', 'Visibility callback.'),
    r(
      'SheetContent.side',
      '"top" | "right" | "bottom" | "left"',
      'Dock edge. Default `right` for Main inspectors. Full-height flex column; compose Header → Body → Footer.',
      'right',
    ),
    r(
      'SheetBody',
      'slot',
      'Required scrollable middle between SheetHeader and SheetFooter (`min-h-0 flex-1 overflow-y-auto`). Side footers use a horizontal action row.',
    ),
    CN,
    MORE,
  ],
  sidebar: [
    r('SidebarProvider.defaultOpen', 'boolean', 'Initial desktop open state.', 'true'),
    r('SidebarProvider.open / onOpenChange', 'boolean / fn', 'Controlled open state.'),
    r('Sidebar.side', '"left" | "right"', 'Dock side.', 'left'),
    r('Sidebar.variant', 'string', 'sidebar | floating | inset', 'sidebar'),
    r('Sidebar.collapsible', 'string', 'offcanvas | icon | none', 'offcanvas'),
    r('useSidebar()', 'hook', 'state, openMobile, setOpen, toggleSidebar, isMobile'),
    CN,
    MORE,
  ],
  skeleton: [
    r('className', 'string', 'Width/height via Tailwind utilities.'),
    MORE,
  ],
  slider: [
    r('value / defaultValue', 'number[]', 'Thumb positions.'),
    r('onValueChange', '(value: number[]) => void', 'Live update while dragging.'),
    r('onValueCommit', '(value: number[]) => void', 'Commit on release.'),
    r('min / max / step', 'number', 'Range and step.', '0 / 100 / 1'),
    r('disabled', 'boolean', 'Non-interactive.', 'false'),
    r('orientation', '"horizontal" | "vertical"', 'Axis.', 'horizontal'),
    CN,
    MORE,
  ],
  sonner: [
    r('theme', '"light" | "dark" | "system"', 'Toast chrome theme.'),
    r('position', 'ToasterProps["position"]', 'Viewport anchor.'),
    r('richColors', 'boolean', 'Semantic toast colors.', 'false'),
    r('expand', 'boolean', 'Expand stack on hover.', 'false'),
    r('duration', 'number', 'Default auto-dismiss (ms).'),
    r('visibleToasts', 'number', 'Max visible toasts.'),
    MORE,
  ],
  spinner: [
    r('className', 'string', 'Size via e.g. size-4.'),
    MORE,
  ],
  statistics: [
    r('StatisticCard', 'ReactNode', 'Root metric surface (article). Compose header + footer slots. Peer cards: horizontal flex row, gap 16 or 24px.'),
    r('StatisticHeader', 'ReactNode', 'Title row + value block.'),
    r('StatisticTitle', 'ReactNode', 'Label + optional Medallion row.'),
    r('StatisticLabel', 'string | ReactNode', 'Metric title (body/14/semibold).'),
    r('StatisticValue', 'string | number | ReactNode', 'Primary value (display/48/bold).'),
    r('StatisticFooter', 'ReactNode', 'Description + action row.'),
    r('StatisticDescription', 'ReactNode', 'Supporting footer text (body/14).'),
    r('StatisticAction', 'ReactNode', 'Footer link — same styles as Link appearance="primary".'),
    r('StatisticHint', 'ReactNode', 'Deprecated alias of StatisticDescription.'),
    r(
      'layout (multiple)',
      'flex row',
      'Display peer StatisticCards horizontally on the same row. Gap: --uds-gap-16 or --uds-gap-24 only. Cards use flex-1 to share width.',
    ),
    CN,
    MORE,
  ],
  status: [
    r('variant', '"neutral" | "success" | "warning" | "error" | "info"', 'Semantic status color style.', 'neutral'),
    r(
      'appearance',
      '"solid" | "outlined" | "text-only"',
      'Preferred / default: "outlined" (border-only, transparent fill). "solid" fills the chip when stronger emphasis is needed; "text-only" drops the container (label + dot only).',
      'outlined',
    ),
    r(
      'color',
      '"pastel" | "default"',
      '"pastel" is a soft tint; "default" is a deeper, more saturated treatment of the same appearance.',
      'pastel',
    ),
    r('size', '"default" | "compact"', 'Default uses 14px type and an 8px dot; compact uses 12px type and a 6px dot.', 'default'),
    r('dot', 'boolean', 'Show/hide leading status indicator dot. In "text-only" appearance the dot uses a distinct (softer or bolder) tone from the label text.', 'true'),
    CN,
    MORE,
  ],
  steps: [
    r('Steps.orientation', '"horizontal" | "vertical"', 'Layout direction; propagated to each Step.', 'horizontal'),
    r(
      'Step.status',
      '"complete" | "active" | "incomplete" | "disabled" | "error" | "warning"',
      'Status used to style the marker, connector lines, and text.',
      'incomplete',
    ),
    r('Step.size', '"default" | "compact"', 'Default shows an 18px marker with a status icon; compact is an 8px dot with no icon.', 'default'),
    r('StepTitle', 'ReactNode', 'Step heading content.'),
    r('StepDescription', 'ReactNode', 'Supporting step details.'),
    CN,
    MORE,
  ],
  switch: [
    r('size', '"default" | "sm"', 'Track height 28px (default) or 20px (sm).', 'default'),
    r('checked', 'boolean', 'Controlled on state.'),
    r('defaultChecked', 'boolean', 'Initial on state.'),
    r('onCheckedChange', '(checked: boolean) => void', 'Toggle callback.'),
    r('disabled', 'boolean', 'Non-interactive.', 'false'),
    r('required', 'boolean', 'Form validation.', 'false'),
    r('name', 'string', 'Form name.'),
    CN,
    MORE,
  ],
  table: [
    r(
      'appearance',
      '"default" | "plain"',
      'Outer container chrome. `default` has border + 4px radius; `plain` removes border/radius. Inside CardContent, border/radius are always cleared.',
      'default',
    ),
    r(
      'containerClassName',
      'string',
      'Classes for the outer scroll/chrome wrapper (`data-slot="table-container"`). Use to override overflow, border, or width.',
    ),
    CN,
    r('children', 'ReactNode', 'TableHeader, TableBody, TableRow, TableCell, etc.'),
    r(
      'TableHead / TableCell padding',
      'spacing',
      'Body py 8px; horizontal interior 4px; first cell left 16–24px; last cell right 16–24px. TableHead height ≥48px (--uds-spacing-48). Defaults: py-8, first:pl-16, last:pr-16.',
      'py-8; first pl-16; last pr-16; head h-48',
    ),
    r(
      'TableHead.wrap / TableCell.wrap',
      'boolean',
      'When true, use whitespace-normal so cell text can wrap. Default false (nowrap).',
      'false',
    ),
    MORE,
  ],
  tabs: [
    r('value / defaultValue', 'string', 'Active tab id.'),
    r('onValueChange', '(value: string) => void', 'Tab change.'),
    r('orientation', '"horizontal" | "vertical"', 'Tab list axis.', 'horizontal'),
    r(
      'TabsList.fill',
      'boolean',
      'Preferred / default false: list stays w-full (strip/underline spans the band); triggers stay condensed. Set true for equal-width flex triggers.',
      'false',
    ),
    r('TabsList.variant', '"default" | "line"', 'Preferred / default: "line" (underlined). "default" is the pill / segmented strip.', 'line'),
    CN,
    MORE,
  ],
  text: [
    r('variant', '"body" | "heading" | "display"', 'Typography group from the UDS type scale.', 'body'),
    r(
      'size',
      'TextSize',
      'Step within the selected group. See `TEXT_BODY_SIZES`, `TEXT_HEADING_SIZES`, and `TEXT_DISPLAY_SIZES`. Defaults to 14 / 24 / 48.',
    ),
    r(
      'lineHeight',
      '"regular" | "tight" | "loose"',
      'Line-height preset from `--uds-type-*` typography tokens.',
      'regular',
    ),
    r('weight', '"regular" | "medium" | "semibold" | "bold"', 'UDS font weight token.', 'regular'),
    r(
      'appearance',
      'TextAppearance',
      'Optional semantic color from `--uds-text-*` tokens (`text-uds-text-*`). See `TEXT_APPEARANCES` export for the full list. When omitted, uses `text-foreground`.',
    ),
    r('as', '"p" | "span" | "div" | "strong" | "em" | "label"', 'Polymorphic root element.', 'p'),
    CN,
    MORE,
  ],
  textarea: [
    r('value / defaultValue', 'string', 'Text content.'),
    r('onChange', 'ChangeEventHandler', 'Change callback.'),
    r('placeholder', 'string', 'Hint text.'),
    r('disabled', 'boolean', 'Non-editable.', 'false'),
    r('readOnly', 'boolean', 'Read-only.', 'false'),
    r('rows', 'number', 'Visible rows.'),
    r('maxLength', 'number', 'Character limit.'),
    CN,
    MORE,
  ],
  'time-input': [
    r('value / defaultValue', 'string', 'Time value in 24-hour `HH:mm` format (e.g. `09:30`).', '"09:30"'),
    r('onValueChange', '(value: string) => void', 'Called when hours, minutes, or period change.'),
    r('period / defaultPeriod', '"AM" | "PM"', '12-hour meridiem segment.', '"AM"'),
    r('onPeriodChange', '(period: "AM" | "PM") => void', 'Called when the meridiem segment is toggled.'),
    r('showTimezone', 'boolean', 'Shows the timezone label after meridiem (linked Figma Timezone boolean).', 'false'),
    r('timezone', 'string', 'Timezone abbreviation when showTimezone is true (linked Figma TEXT property).', '"EST"'),
    r('inputSize', '"default" | "sm"', 'Default 44px shell; sm uses 36px compact shell.', 'default'),
    r('autoComplete', 'string', 'Time entry autofill hint.', 'off'),
    CN,
    MORE,
  ],
  'time-step-input': [
    r('type', '"text"', 'Read-only text field that displays the selected time label.', 'text'),
    r('value / defaultValue', 'string', 'Selected time value in 24-hour `HH:mm` format (e.g. `13:30`).'),
    r('onValueChange', '(value: string) => void', 'Called when a time option is picked from the dropdown.'),
    r('stepMinutes', 'number', 'Minute interval used to generate the dropdown options.', '30'),
    r('startTime / endTime', 'string', 'Range bounds in 24-hour `HH:mm` format.', '"08:00" / "18:00"'),
    r('format12Hour', 'boolean', 'Displays dropdown labels as 12-hour times with AM/PM.', 'true'),
    r('showTimezone', 'boolean', 'Shows the timezone label beside the value (linked Figma Timezone boolean).', 'false'),
    r('timezone', 'string', 'Timezone abbreviation when showTimezone is true (linked Figma TEXT property).', '"EST"'),
    r('autofilled', 'boolean', 'Shows the same tint + sparkle icon as autofilled inputs. No real <input> backs this control, so it must be set explicitly rather than detected.', 'false'),
    CN,
    MORE,
  ],
  'token-input': [
    r('inputSize', '"default" | "sm"', 'Default uses Button xs / Small (32px) chips; sm uses 2x-sm / Extra Small (24px) for compact shells.', 'default'),
    r('type', '"text"', 'Internal editor input type.', 'text'),
    r('tokens / defaultTokens', 'string[]', 'Controlled or initial token chip list.'),
    r('onTokensChange', '(tokens: string[]) => void', 'Called whenever tokens are added or removed.'),
    r('value / defaultValue', 'string', 'Controlled or initial draft text before it is committed into a token chip.'),
    r('maxTokens', 'number', 'Maximum number of tokens allowed.'),
    r('allowDuplicates', 'boolean', 'Allow duplicate token labels.', 'false'),
    r('separators', 'string[]', 'Keys that commit draft text into a token (e.g. Enter, comma).', '[",", "Enter"]'),
    r('autoComplete', 'string', 'Prevents browser autofill on secret/token fields.', 'off'),
    r('autoCapitalize', 'string', 'Prevents mobile capitalization changes.', 'none'),
    r('autoCorrect', 'string', 'Disables mobile auto-correction.', 'off'),
    r('spellCheck', 'boolean', 'Disables spell-check underlines on token strings.', 'false'),
    CN,
    MORE,
  ],
  toggle: [
    r('pressed / defaultPressed', 'boolean', 'Toggle pressed state.'),
    r('onPressedChange', '(pressed: boolean) => void', 'Press callback.'),
    r('disabled', 'boolean', 'Non-interactive.', 'false'),
    r('variant', 'string', 'default | outline', 'default'),
    r('size', 'string', 'default | sm | lg', 'default'),
    CN,
    MORE,
  ],
  'toggle-group': [
    r('type', '"single" | "multiple"', 'One or many selections.'),
    r('value / defaultValue', 'string | string[]', 'Selected value(s).'),
    r('onValueChange', '(value) => void', 'Selection change.'),
    r('variant', 'string', 'default | outline', 'default'),
    r('size', 'string', 'default | sm | lg', 'default'),
    r('spacing', 'number', 'Gap between items.'),
    CN,
    MORE,
  ],
  toolbar: [
    r('size', '"default" | "lg"', 'Bar height: default 44px; lg 56px for stacked title + description.', 'default'),
    r('ToolbarStart', 'ReactNode', 'Leading actions (buttons, links, icon controls).'),
    r('ToolbarCenter', 'ReactNode', 'Centered title / metadata column.'),
    r('ToolbarTitle', 'ReactNode', 'Primary label in the center.'),
    r('ToolbarDescription', 'ReactNode', 'Secondary metadata under the title.'),
    r('ToolbarEnd', 'ReactNode', 'Trailing actions.'),
    r('ToolbarGroup', 'ReactNode', 'Cluster controls inside Start or End.'),
    r('ToolbarDivider', 'visual separator', 'Thin vertical divider between groups.'),
    CN,
    MORE,
  ],
  tooltip: [
    r('open / onOpenChange', 'boolean / fn', 'Tooltip visibility.'),
    r('delayDuration', 'number', 'Show delay (ms).'),
    r('disableHoverableContent', 'boolean', 'Pointer cannot enter content.', 'false'),
    CN,
    MORE,
  ],
  'url-input': [
    r('type', '"text"', 'Renders an Input Group-style URL field with a protocol addon and domain/path text input.', 'text'),
    r('protocol', 'string', 'Leading static prefix shown in the left addon.', '"https://"'),
    r('placeholder', 'string', 'Domain/path placeholder for the editable field.', '"example.com"'),
    r('inputSize', '"default" | "sm"', 'Shared size for the wrapper and inner URL field.', 'default'),
    r('inputMode', 'string', 'Hints URL keyboard layout on mobile devices.', 'url'),
    r('autoComplete', 'string', 'URL autofill hint.', 'url'),
    CN,
    MORE,
  ],
}

export function getShadcnComponentProps(slug: ShadcnUiSlug): PropDefinition[] {
  return SHADCN_COMPONENT_PROPS[slug]
}
