import { DOT_STATUS_VARIANTS } from '@chg-ds/unified-design-system'
import { DOCTOR_AVATAR_BY_FIRST_NAME } from '@/lib/doctor-avatars'

import type { ShadcnUiSlug } from './shadcn-ui-registry'
import type { PropDefinition } from './types'

const r = (
  name: string,
  type: string,
  description: string,
  defaultValue?: string,
): PropDefinition => ({ name, type, description, default: defaultValue })

/** Props forwarded to DOM / Radix / library beyond the rows above. */
const MORE: PropDefinition = r(
  '…',
  'varies',
  'Additional props are forwarded to the underlying element or primitive. See `src/components/ui/<slug>.tsx` for the full TypeScript type.',
)

const CN = r('className', 'string', 'Merged with `cn()` for layout and theme styling.')

/** Full union for PropsTable; kept in sync with `DoctorFirstName` in `doctor-avatars`. */
const DOCTOR_FIRST_NAME_PROP_TYPE = (
  Object.keys(DOCTOR_AVATAR_BY_FIRST_NAME) as (keyof typeof DOCTOR_AVATAR_BY_FIRST_NAME)[]
)
  .slice()
  .sort()
  .map((name) => `"${name}"`)
  .join(' | ')

const DOT_STATUS_VARIANT_PROP_TYPE = DOT_STATUS_VARIANTS.map((v) => `"${v}"`).join(' | ')

export const SHADCN_COMPONENT_PROPS: Record<ShadcnUiSlug, PropDefinition[]> = {
  accordion: [
    r(
      'variant',
      '"boxed" | "divided"',
      '`boxed`: outer border, 4px radius, dividers between items, light gray trigger strip. `divided`: dividers only, no outer frame.',
      'divided',
    ),
    r('type', '"single" | "multiple"', 'How many sections may be open at once.'),
    r('collapsible', 'boolean', 'In single mode, allow closing the open item.', 'false'),
    r('value', 'string | string[]', 'Controlled open item value(s).'),
    r('defaultValue', 'string | string[]', 'Initial open value(s) when uncontrolled.'),
    r('onValueChange', '(value: string) => void', 'Fired when the open section changes.'),
    r('AccordionItem.value', 'string', 'Required unique id for each item.'),
    CN,
    MORE,
  ],
  alert: [
    r('variant', '"default" | "destructive"', 'Semantic tone.', 'default'),
    r(
      'children',
      'ReactNode',
      'Optional leading `<Medallion />` or SVG, then `AlertContent` wrapping `AlertTitle` + `AlertDescription` (recommended). Title and description may still be direct children for backward compatibility.',
      '—',
    ),
    CN,
    MORE,
  ],
  'alert-dialog': [
    r('open', 'boolean', 'Controls dialog visibility.'),
    r('onOpenChange', '(open: boolean) => void', 'Visibility change callback.'),
    r(
      'AlertDialogMedia (slot)',
      'ReactNode',
      'Optional header icon; chrome (size, radius, colors) comes from theme: `src/styles/uds-chrome-media.css` via `[data-slot="alert-dialog-media"]`.',
    ),
    CN,
    MORE,
  ],
  'aspect-ratio': [
    r('ratio', 'number', 'Width / height ratio (e.g. 16/9).'),
    CN,
    MORE,
  ],
  avatar: [
    r(
      'size',
      "'xs' | 'sm' | 'default' | 'lg'",
      'Square size: 32px / 36px / 48px / 64px.',
      'default',
    ),
    r(
      'doctor',
      DOCTOR_FIRST_NAME_PROP_TYPE,
      'On `DoctorAvatar` / `DoctorAvatarImage` only: lowercase first name mapped to a portrait in `public/avatars/doctors/`.',
    ),
    r('AvatarImage.src', 'string', 'Image URL (omit on `DoctorAvatarImage`; use `doctor` instead).'),
    r('AvatarImage.alt', 'string', 'Accessible description.'),
    r('AvatarFallback.delayMs', 'number', 'Delay before showing fallback.', '600'),
    r(
      'AvatarStatus.variant',
      DOT_STATUS_VARIANT_PROP_TYPE,
      'Bottom-right `DotStatus` (always `size="medium"` / 10px). Place `AvatarStatus` after image/fallback.',
      'green',
    ),
    r('AvatarStatus.outline', 'boolean', 'Forwarded to `DotStatus` ring treatment.', 'false'),
    r(
      'status',
      'DotStatusVariant',
      '`DoctorAvatar` only: shorthand for `AvatarStatus`; omit to hide the dot. Values match `AvatarStatus.variant` above.',
      '—',
    ),
    r('statusOutline', 'boolean', '`DoctorAvatar` only: passed to `AvatarStatus`.', 'false'),
    r(
      'AvatarCameraAction',
      'button + icon',
      '`xs`/`sm`: 16×16, nudge 2px right + down; `default`/`lg`: 20×20, nudge 4px right + down. UDS gray fill, black camera icon (inverted in dark). Forwards `<button>` props; default `type="button"`, Phosphor `Camera`; override with `icon`.',
      '—',
    ),
    r(
      'cameraAction',
      'AvatarCameraActionProps',
      '`DoctorAvatar` only: spread onto `AvatarCameraAction` (omit prop to hide).',
      '—',
    ),
    CN,
    MORE,
  ],
  badge: [
    r(
      'variant',
      'string',
      'Legacy shadcn cva styles (default, secondary, destructive, outline, …) used only when `accent` is omitted. Prefer `accent` + `appearance` for UDS badges.',
      'default',
    ),
    r(
      'shape',
      "'pill' | 'rect'",
      '`pill`: fully rounded ends (`rounded-4xl`). `rect`: 2px corner radius (`rounded-[2px]`).',
      'pill',
    ),
    r(
      'size',
      "'default' | 'sm'",
      '`sm`: shorter control (`h-5`), tighter horizontal padding, same `text-xs` label as default with `leading-none`, and smaller icons (`h-2.5 w-2.5`).',
      'default',
    ),
    r(
      'accent',
      'BadgeAccent | undefined',
      'UDS accent family: transparent, neutral, chromatic hues, inverse. When set, drives colors; `variant` is ignored.',
    ),
    r(
      'appearance',
      "'subtle' | 'pastel' | 'outlined' | 'solid'",
      'Label-only badge treatment when `accent` is set.',
      'solid',
    ),
    r(
      'icon',
      'ReactNode',
      'Leading/trailing icon (Phosphor, etc.); pairs with `iconPlacement`. Ignored when `asChild` is true — put `data-icon="inline-start|inline-end"` on an icon child instead.',
    ),
    r('iconPlacement', "'inline-start' | 'inline-end'", 'Side of the label for `icon`.', 'inline-start'),
    r('asChild', 'boolean', 'Merge onto child via Slot.', 'false'),
    CN,
    MORE,
  ],
  breadcrumb: [
    r(
      'BreadcrumbSeparator.children',
      'ReactNode',
      'Optional. Default `/` with `text-neutral-400`, matching documentation breadcrumb chrome; override for icons or other markers.',
    ),
    CN,
    MORE,
  ],
  branding: [
    r(
      'appearance',
      'BrandingAppearance',
      'Product or brand variant: Connect, CHG (Unified Design System SVGs + Connect-aligned tokens via data-brand), Locumsmart, Wireframe, MyWeatherby, MyCompHealth, Modio, or Design System.',
      'Wireframe',
    ),
    r(
      'symbol',
      'boolean',
      'When true, renders the square mark (64×64). When false, the full wordmark (200×80).',
      'false',
    ),
    r(
      'wordmarkAlign',
      "'start' | 'center'",
      'Wordmark only: horizontal alignment of SVG inside the frame (`center` for nav / hero lockups).',
      "'start'",
    ),
    CN,
    MORE,
  ],
  button: [
    r('variant', 'enum', 'default | outline | secondary | ghost | destructive | link', 'default'),
    r('size', 'enum', 'default | xs | sm | lg | icon | icon-xs | icon-sm | icon-lg', 'default'),
    r('asChild', 'boolean', 'Render as child element.', 'false'),
    CN,
    MORE,
  ],
  'button-group': [
    r('orientation', '"horizontal" | "vertical"', 'Stack direction.', 'horizontal'),
    CN,
    MORE,
  ],
  calendar: [
    r('mode', '"single" | "range" | "multiple"', 'Selection mode.'),
    r('selected / defaultSelected', 'Date | DateRange | Date[]', 'Current or initial selection.'),
    r('onSelect', '(date) => void', 'Selection change handler.'),
    r('disabled', 'Matcher | Matcher[]', 'Dates that cannot be selected.'),
    r('locale', 'Locale', 'date-fns locale for labels.'),
    CN,
    MORE,
  ],
  card: [
    CN,
    r('children', 'ReactNode', 'Header, content, footer slots.'),
    MORE,
  ],
  chart: [
    r('ChartContainer.config', 'ChartConfig', 'Series labels, colors, and theme mapping.'),
    r('ChartContainer.initialDimension', '{ width; height }', 'SSR / first paint size.'),
    CN,
    MORE,
  ],
  'check-list': [
    r('CheckListControl.id', 'string', 'Unique id linking checkbox and label.'),
    r('CheckListControl.label', 'ReactNode', 'Primary task label.'),
    r('CheckListControl.description', 'ReactNode', 'Optional secondary helper text.'),
    r('CheckListControl.checked', 'boolean', 'Controlled checked state.'),
    r('CheckListControl.onCheckedChange', '(checked) => void', 'Checkbox state change callback.'),
    CN,
    MORE,
  ],
  checkbox: [
    r('checked', 'boolean | "indeterminate"', 'Controlled state.'),
    r('defaultChecked', 'boolean', 'Initial state when uncontrolled.'),
    r('onCheckedChange', '(checked: boolean) => void', 'Change callback.'),
    r('disabled', 'boolean', 'Non-interactive.', 'false'),
    r('required', 'boolean', 'Participates in form validation.', 'false'),
    r('name', 'string', 'Form field name.'),
    r('value', 'string', 'Submitted value when checked.'),
    CN,
    MORE,
  ],
  collapsible: [
    r('open', 'boolean', 'Controlled open state.'),
    r('onOpenChange', '(open: boolean) => void', 'Open state callback.'),
    r('defaultOpen', 'boolean', 'Initial open when uncontrolled.', 'false'),
    r('variant', '"boxed" | "divided"', 'Chrome aligned with Accordion.', '"divided"'),
    r('CollapsibleContent.contentClassName', 'string', 'Classes merged onto the inner panel (default `px-4 pt-0 pb-3`).', '—'),
    CN,
    MORE,
  ],
  combobox: [
    r('items', 'readonly any[]', 'Values used to filter the list and drive `ComboboxEmpty`; pass the same values as `ComboboxItem` for filterable lists.', '—'),
    r('value / defaultValue', 'string', 'Selected option value.'),
    r('onValueChange', '(value: string) => void', 'Selection callback.'),
    r('disabled', 'boolean', 'Disable the control.', 'false'),
    CN,
    MORE,
  ],
  command: [
    r('value / defaultValue', 'string', 'Active item value (cmdk).'),
    r('onValueChange', '(value: string) => void', 'Selection change.'),
    r('filter', '(value, search) => number', 'Custom filter function.'),
    r('shouldFilter', 'boolean', 'Enable built-in filtering.', 'true'),
    r('loop', 'boolean', 'Keyboard wrap at ends.', 'false'),
    CN,
    MORE,
  ],
  'context-menu': [
    r('open / onOpenChange', 'boolean / fn', 'Controlled menu visibility.'),
    r('modal', 'boolean', 'Modal focus trap behavior.', 'true'),
    CN,
    MORE,
  ],
  'description-list': [
    r('DescriptionRow', 'layout helper', 'Wrap each term/detail pair with a semantic grouping wrapper.'),
    r('DescriptionTerm', 'dt', 'Term label cell.'),
    r('DescriptionDetail', 'dd', 'Value/detail cell.'),
    CN,
    MORE,
  ],
  dialog: [
    r('open', 'boolean', 'Controlled visibility.'),
    r('onOpenChange', '(open: boolean) => void', 'Visibility callback.'),
    r('defaultOpen', 'boolean', 'Initial open.', 'false'),
    CN,
    MORE,
  ],
  direction: [
    r('dir / direction', '"ltr" | "rtl"', 'Document direction for descendants.'),
    MORE,
  ],
  'dot-status': [
    r(
      'variant',
      DOT_STATUS_VARIANT_PROP_TYPE,
      'Fill from the UDS accent scale; `neutral` and `inverse` are semantic; `celery` uses the emerald accent (yellow-green).',
      'green',
    ),
    r(
      'size',
      '"small" | "medium" | "large"',
      'Dot size: 8px / 10px / 12px (`size-2` / `size-2.5` / `size-3`) — medium and large are tighter vs small than the prior 12/16 scale.',
      'medium',
    ),
    r('outline', 'boolean', 'Adds a 2px ring using `--uds-border-primary` with background offset.', 'false'),
    CN,
    MORE,
  ],
  drawer: [
    r('open', 'boolean', 'Drawer visibility.'),
    r('onOpenChange', '(open: boolean) => void', 'Visibility callback.'),
    r('dismissible', 'boolean', 'Allow swipe / overlay close.', 'true'),
    CN,
    MORE,
  ],
  'dropdown-menu': [
    r('open / onOpenChange', 'boolean / fn', 'Menu visibility.'),
    r('modal', 'boolean', 'Modal behavior.', 'true'),
    CN,
    MORE,
  ],
  'date-input': [
    r('type', '"text"', 'Preset to a text field with a single-date calendar picker.', 'text'),
    r('placeholder', 'string', 'Defaults to `mm/dd/yyyy`.'),
    r('date', 'Date | undefined', 'Controlled selected date.'),
    r('defaultDate', 'Date | undefined', 'Initial selected date (uncontrolled mode).'),
    r(
      'onDateChange',
      '(date: Date | undefined) => void',
      'Fires when the date changes from the calendar or from typing digits only (auto-formatted as `mm/dd/yyyy`, committed on blur; invalid input reverts).',
    ),
    r(
      'yearSelection',
      "'grid' | 'caption'",
      'Default `grid`: caption shows month and year each with a caret; open a 12-cell month table (arrows change year) or a 12-year table (arrows page years). In month/year grids, pick a value to return to days. `caption` uses DayPicker `captionLayout` (e.g. `dropdown-years`) instead.',
      'grid',
    ),
    r(
      'captionLayout',
      "'label' | 'dropdown' | 'dropdown-months' | 'dropdown-years'",
      'When `yearSelection` is `caption`, forwarded to `Calendar` / DayPicker. Ignored when `yearSelection` is `grid`.',
      'dropdown-years',
    ),
    r('startMonth', 'Date', 'First month / minimum year in navigation bounds.', '100 years before current year'),
    r('endMonth', 'Date', 'Last month / maximum year in navigation bounds.', '50 years after current year'),
    r('inputMode', 'string', 'Hints numeric keypad for date entry formatting.', 'numeric'),
    r('autoComplete', 'string', 'Date autocomplete hint for browser autofill.', 'bday'),
    CN,
    MORE,
  ],
  'date-range-input': [
    r('type', '"text"', 'Preset to a text field with a range-calendar picker.', 'text'),
    r('separator', 'string', 'Display separator between start/end dates.', '" – "'),
    r('placeholder', 'string', 'Defaults to `mm/dd/yyyy – mm/dd/yyyy`.'),
    r('range', 'DateRange | undefined', 'Controlled selected date range.'),
    r('defaultRange', 'DateRange | undefined', 'Initial selected date range (uncontrolled mode).'),
    r(
      'onRangeChange',
      '(range: DateRange | undefined) => void',
      'Fires when the range changes from the calendar or from typing digits only (two `mm/dd/yyyy` segments auto-formatted; `separator` is inserted after the first 8 digits; committed on blur; invalid input reverts).',
    ),
    r(
      'yearSelection',
      "'grid' | 'caption'",
      'Default `caption`: DayPicker label captions (no month/year `<select>`; no month/year grid). Use `grid` for the same caption/grid UX as `DateInput`.',
      'caption',
    ),
    r(
      'captionLayout',
      "'label' | 'dropdown' | 'dropdown-months' | 'dropdown-years'",
      'When `yearSelection` is `caption`, forwarded to `Calendar` / DayPicker. Default `label` (text caption + nav arrows only). Ignored for `grid`.',
      'label',
    ),
    r('startMonth', 'Date', 'First month / minimum year in navigation bounds.', '100 years before current year'),
    r('endMonth', 'Date', 'Last month / maximum year in navigation bounds.', '50 years after current year'),
    r('inputMode', 'string', 'Hints numeric keypad for date entry formatting.', 'numeric'),
    CN,
    MORE,
  ],
  empty: [
    r(
      'EmptyMedia (slot)',
      'ReactNode',
      'Icon or illustration; chrome comes from theme: `src/styles/uds-chrome-media.css` via `[data-slot="empty-icon"]`.',
    ),
    CN,
    r('children', 'ReactNode', 'Title, description, media, actions.'),
    MORE,
  ],
  field: [
    r('FieldSet.name', 'string', 'Group name for nested controls.'),
    r('FieldLegend', 'ReactNode', 'Accessible group label.'),
    r('FieldLabel.htmlFor', 'string', 'Associates label with control id.'),
    CN,
    MORE,
  ],
  'file-upload': [
    r('onFileSelect', '(files: File[]) => void', 'Called when files are selected via click or drag/drop.'),
    r(
      'size',
      '"default" | "small" | "xs"',
      'Dropzone scale; `xs` is a single short row (xs medallion, tight padding, instruction + helper on one line when defaults apply).',
      'default',
    ),
    r('multiple', 'boolean', 'Allow selecting multiple files from chooser and drop.', 'false'),
    r('accept', 'string', 'Native file input accept filter (e.g. `.pdf,image/*`).'),
    r('instructionText', 'ReactNode', 'Primary upload instruction displayed in the dropzone.'),
    r('helperText', 'ReactNode', 'Secondary helper or validation message below the instruction; can be plain text or custom markup.'),
    r('helperTextClassName', 'string', 'Optional classes merged onto the helper text element for typography overrides.'),
    CN,
    MORE,
  ],
  'file-upload-cards': [
    r('items / defaultItems', 'FileUploadCardItem[]', 'Controlled or initial card models for rich status/progress rendering.'),
    r('files / defaultFiles', 'File[]', 'Simple file-only mode; files are mapped into default card items.'),
    r('onItemsChange', '(items: FileUploadCardItem[]) => void', 'Called whenever card items are added, removed, or replaced.'),
    r('onFilesChange', '(files: File[]) => void', 'Called with the `File` subset whenever card items change.'),
    r('FileUploadCardItem.status', '"idle" | "uploading" | "success" | "error" | "disabled"', 'Per-card state token used for status badge and interaction behavior.', '"idle"'),
    r('FileUploadCardItem.progress', 'number', 'Upload progress percentage shown when status is `uploading`.', '0'),
    r('FileUploadCardItem.errorMessage', 'string', 'Inline error text shown when status is `error`.'),
    r('onRetry / onView / onDownload', '(item) => void', 'Optional action callbacks for retry/view/download controls on each card.'),
    r('helperText', 'ReactNode', 'Helper copy shown in the upload dropzone.', '"PDF, DOCX, PNG up to 10MB each"'),
    r('multiple', 'boolean', 'Allows selecting multiple files per browse/drop action.', 'true'),
    r(
      'density',
      "'default' | 'compact'",
      '`compact`: tighter list spacing, smaller thumbnails and actions, `Badge size="sm"`, and defaults the dropzone to `size="xs"` unless you pass `size` explicitly.',
      'default',
    ),
    CN,
    MORE,
  ],
  footer: [
    r('copyright', 'string', 'Copyright text displayed on the left. Defaults to current-year CHG Management notice.'),
    r('links', 'FooterLink[]', 'Navigation links displayed on the right. Each entry has `label` and `href`.'),
    r('children', 'ReactNode', 'Custom content that replaces the default copyright + links layout.'),
    CN,
    MORE,
  ],
  header: [
    r('children', 'ReactNode', 'Custom leading content that replaces the default SearchInput (e.g. breadcrumbs, page title).'),
    r('trailing', 'ReactNode', 'Right-aligned trailing slot for utility actions (icon buttons, avatar, dropdowns).'),
    r('searchProps', 'SearchInputProps', 'Props forwarded to the default SearchInput. Ignored when `children` is provided.'),
    CN,
    MORE,
  ],
  'hover-card': [
    r('open / onOpenChange', 'boolean / fn', 'Popover visibility.'),
    r('openDelay / closeDelay', 'number', 'Hover timing (ms).'),
    CN,
    MORE,
  ],
  input: [
    r('type', 'string', 'HTML input type.', 'text'),
    r('value / defaultValue', 'string', 'Controlled / initial value.'),
    r('onChange', 'ChangeEventHandler', 'Input change.'),
    r('placeholder', 'string', 'Hint text.'),
    r('disabled', 'boolean', 'Non-editable.', 'false'),
    r('readOnly', 'boolean', 'Read-only field.', 'false'),
    r('required', 'boolean', 'Required for forms.', 'false'),
    r('name / id', 'string', 'Form identity.'),
    CN,
    MORE,
  ],
  'input-group': [
    CN,
    r('children', 'ReactNode', 'Addon + input composition.'),
    MORE,
  ],
  'input-otp': [
    r('maxLength', 'number', 'Number of OTP cells.'),
    r('value / onChange', 'string / fn', 'Controlled value.'),
    r('disabled', 'boolean', 'Disable entry.', 'false'),
    CN,
    MORE,
  ],
  item: [
    r('variant', 'string', 'default | outline | muted', 'default'),
    r('size', 'string', 'default | sm', 'default'),
    CN,
    MORE,
  ],
  kbd: [
    CN,
    r('children', 'ReactNode', 'Key cap label(s).'),
    MORE,
  ],
  label: [
    r('htmlFor', 'string', 'Target control id.'),
    r(
      'RadioGroupLabel',
      'typeof Label',
      'Use `RadioGroupLabel` from `@chg-ds/unified-design-system`: UDS body-16 regular for `RadioGroupItem` captions.',
    ),
    CN,
    MORE,
  ],
  layout: [
    r(
      'direction',
      '"row" | "col" | "row-reverse" | "col-reverse" | CSS flex-direction',
      '`col` / `col-reverse` map to `column` / `column-reverse`. Any other string is forwarded as `flexDirection`.',
      'row',
    ),
    r('alignItems', 'CSS align-items', 'Flex cross-axis alignment (e.g. `center`, `stretch`, `flex-start`).'),
    r('justifyContent', 'CSS justify-content', 'Flex main-axis distribution (e.g. `space-between`, `center`).'),
    r(
      'gap',
      'number | string',
      'Number: theme spacing index (`n × 0.25rem`, same as Tailwind `gap-*`). String: raw CSS `gap` value.',
    ),
    r(
      'wrap',
      'boolean | "nowrap" | "wrap" | "wrap-reverse"',
      '`true` / `false` map to `wrap` / `nowrap`. Strings are passed through as CSS `flex-wrap`.',
    ),
    r(
      'as',
      'keyof JSX.IntrinsicElements',
      'Intrinsic HTML tag for the flex root (e.g. `div`, `ul`, `section`).',
      'div',
    ),
    CN,
    MORE,
  ],
  link: [
    r('external', 'boolean', 'Applies external link defaults (`target`, `rel`) and icon.', 'false'),
    r('showExternalIcon', 'boolean', 'Shows trailing external-link icon when `external` is true.', 'true'),
    r('href', 'string', 'Destination URL.'),
    CN,
    MORE,
  ],
  medallion: [
    r('color', 'MedallionColor', 'UDS accent/neutral key (`MEDALLION_COLORS`).'),
    r(
      'tone',
      `'pastel' | 'solid'`,
      '`pastel` — `MEDALLION_PASTEL_PALETTE` (tinted surface + deeper icon; inverts in dark). `solid` — `MEDALLION_SOLID_PALETTE` (`500` ramp fill + white icon).',
      'pastel',
    ),
    r('icon', 'ReactNode', 'Centered glyph (Phosphor recommended).'),
    r('size', `'xs' | 'sm' | 'default' | 'lg' | 'xl'`, 'Container and icon scale.', 'default'),
    r(
      'shape',
      `'circle' | 'square' | 'rounded'`,
      '`rounded` uses a 12px corner radius.',
      'circle',
    ),
    CN,
    MORE,
  ],
  menubar: [
    r('value / defaultValue', 'string', 'Active submenu value.'),
    r('onValueChange', '(value: string) => void', 'Submenu change.'),
    CN,
    MORE,
  ],
  'micro-calendar': [
    r('value', 'Date', 'Selected day (highlight).'),
    r('today', 'Date', 'Optional stand-in for the real current day (today styling and collapsed-week row).'),
    r('month', 'Date', 'Month shown (first of month); syncs from props when the reference month changes.'),
    r('onMonthChange', '(month: Date) => void', 'Optional callback when the displayed month changes from navigation.'),
    r('onDateSelect', '(date: Date) => void', 'Called when a selectable day is activated.'),
    r('unavailableDates', 'Date[]', 'Days shown as unavailable (not selectable).', '[]'),
    r(
      'dateData',
      'Record<string, MicroCalendarDateData>',
      'Per-day flags keyed by local `YYYY-MM-DD`; values may include `travel` and `onAssignment` for markers.',
      '{}',
    ),
    r('defaultExpanded', 'boolean', 'Whether the grid starts expanded or as a single-week strip.', 'true'),
    r('showLegend', 'boolean', 'Show the legend row when expanded.', 'true'),
    r('showExpandCollapse', 'boolean', 'Show the bottom caret toggle.', 'true'),
    r('MicroCalendarTile — date', 'Date', 'Single-day chip: calendar date to display.', 'new Date()'),
    r('MicroCalendarTile — locale', 'string', 'Locale for weekday and month abbreviations on the tile.', 'en-US'),
    CN,
    MORE,
  ],
  'native-select': [
    r('inputSize', '"default" | "sm"', 'Height and typography; matches Input.', 'default'),
    r('value / defaultValue', 'string', 'Selected option.'),
    r('onChange', 'ChangeEventHandler', 'Change callback.'),
    r('disabled', 'boolean', 'Disable select.', 'false'),
    r('required', 'boolean', 'Form required.', 'false'),
    r('name', 'string', 'Form name.'),
    CN,
    MORE,
  ],
  'navigation-menu': [
    r('value / defaultValue', 'string', 'Active item.'),
    r('onValueChange', '(value: string) => void', 'Selection callback.'),
    r('delayDuration', 'number', 'Hover open delay (ms).'),
    CN,
    MORE,
  ],
  'number-input': [
    r('type', '"number"', 'Preset to numeric input type.', 'number'),
    r('inputMode', 'string', 'Hints decimal keypad on mobile devices.', 'decimal'),
    r('step', 'number | string', 'Numeric step increment for controls and validation.', 'any'),
    CN,
    MORE,
  ],
  pagination: [
    CN,
    r('children', 'ReactNode', 'PaginationItem / Link composition.'),
    MORE,
  ],
  'password-input': [
    r('type', '"password" | "text"', 'Toggles between masked and visible states via the eye button.', '"password"'),
    r('visible', 'boolean | undefined', 'Controlled visibility state (text when true).'),
    r('defaultVisible', 'boolean', 'Initial visibility in uncontrolled mode.', 'false'),
    r('onVisibleChange', '(visible: boolean) => void', 'Fires when the eye toggle is pressed.'),
    r('autoComplete', 'string', 'Password manager and browser autofill hint.', 'current-password'),
    CN,
    MORE,
  ],
  'phone-input': [
    r('type', '"tel"', 'Preset to telephone input type.', 'tel'),
    r('value / defaultValue', 'string | number', 'Raw digits or formatted phone string. Component normalizes to digits and re-formats on render.'),
    r('maxDigits', 'number', 'Maximum number of numeric digits kept from input.', '10'),
    r('onValueChange', '(digits: string, formattedValue: string) => void', 'Fires whenever digits change after input sanitation and formatting.'),
    r('onChange', 'ChangeEventHandler', 'Called after formatting; event currentTarget value is formatted text.'),
    r('inputMode', 'string', 'Hints phone keypad on mobile devices; non-digit key presses are blocked.', 'tel'),
    r('autoComplete', 'string', 'Telephone autofill hint.', 'tel'),
    CN,
    MORE,
  ],
  popover: [
    r('open / onOpenChange', 'boolean / fn', 'Popover visibility.'),
    r('modal', 'boolean', 'Modal focus behavior.', 'false'),
    CN,
    MORE,
  ],
  progress: [
    r('value', 'number | null', '0–100 completion; null for indeterminate.'),
    r('max', 'number', 'Maximum value.', '100'),
    CN,
    MORE,
  ],
  'progress-circles': [
    r('ProgressCircle.value', 'number', 'Progress percentage from 0 to 100.'),
    r('ProgressCircle.size', 'number', 'Circle diameter in px.', '72'),
    r('ProgressCircle.strokeWidth', 'number', 'Stroke width in px.', '8'),
    r('ProgressCircle.label', 'ReactNode', 'Custom label below the circle.'),
    CN,
    MORE,
  ],
  'radio-group': [
    r('value / defaultValue', 'string', 'Selected item value.'),
    r('onValueChange', '(value: string) => void', 'Change callback.'),
    r('disabled', 'boolean', 'Disable entire group.', 'false'),
    r('name', 'string', 'Form name.'),
    r('orientation', '"horizontal" | "vertical"', 'Layout.', 'vertical'),
    CN,
    MORE,
  ],
  resizable: [
    r('orientation', '"horizontal" | "vertical"', 'Resize axis.', 'horizontal'),
    r('Panel.defaultSize', 'number', 'Initial size percentage.'),
    r('Panel.minSize / maxSize', 'number', 'Size constraints.'),
    CN,
    MORE,
  ],
  'scroll-area': [
    r('type', '"auto" | "always" | "scroll" | "hover"', 'Scrollbar visibility.', 'hover'),
    r('scrollHideDelay', 'number', 'Delay before hiding (ms).'),
    CN,
    MORE,
  ],
  'search-input': [
    r('variant', '"default" | "shortcut"', '`shortcut`: show a keyboard hint before the search icon.', 'default'),
    r('shortcut', 'ReactNode', 'Custom hint when `variant` is `shortcut` (default: ⌘ + K).'),
    r('ariaKeyShortcuts', 'string', 'Optional `aria-keyshortcuts` override when `variant` is `shortcut`.'),
    r('type', '"search"', 'Preset to browser search field behavior.', 'search'),
    r('submitButtonType', '"submit" | "button" | "reset"', 'Type for the trailing magnifying-glass action button.', 'submit'),
    r('submitButtonAriaLabel', 'string', 'Accessible label for the icon submit button.', 'Submit search'),
    r('onSubmitButtonClick', 'MouseEventHandler<HTMLButtonElement>', 'Called when the trailing icon button is pressed.'),
    r('hideSubmitButton', 'boolean', 'Hides the trailing icon button and removes extra right padding.', 'false'),
    r('autoComplete', 'string', 'Disables aggressive autofill in query-style fields.', 'off'),
    CN,
    MORE,
  ],
  select: [
    r('SelectTrigger.inputSize', '"default" | "sm"', 'Trigger height and typography; matches Input.', 'default'),
    r('value / defaultValue', 'string', 'Selected value.'),
    r('onValueChange', '(value: string) => void', 'Change callback.'),
    r('open / onOpenChange', 'boolean / fn', 'Dropdown visibility.'),
    r('disabled', 'boolean', 'Disable control.', 'false'),
    r('required', 'boolean', 'Form validation.', 'false'),
    r('name', 'string', 'Form name.'),
    r(
      'SelectContent.searchable',
      'boolean',
      'When true, shows a search field in the dropdown and filters options by label (`textValue` or string children). Off by default.',
      'false',
    ),
    r('SelectContent.searchPlaceholder', 'string', 'Visible hint text in the search field when `searchable`.', 'Search…'),
    r(
      'SelectContent.searchAriaLabel',
      'string',
      'Accessible name for the filter field (required for WCAG; do not rely on `placeholder` alone).',
      'Filter options',
    ),
    r(
      'SelectContent.searchAutoFocus',
      'boolean',
      'When `searchable`, focuses the search input after the menu opens.',
      'true',
    ),
    r(
      'SelectContent.searchFilter',
      '(query, label, itemValue) => boolean',
      'Optional custom filter when `searchable`; default is case-insensitive substring on `label`.',
      '—',
    ),
    CN,
    MORE,
  ],
  separator: [
    r(
      'variant',
      '"default" | "label" | "band"',
      '`default`: Radix line. `label`: horizontal rule with a bordered pill (`bg-background`) and optional `labelAlign`. `band`: 8px UDS neutral strip with top/bottom `uds-border-secondary` rules.',
      'default',
    ),
    r('orientation', '"horizontal" | "vertical"', 'Divider axis (`default` variant only).', 'horizontal'),
    r('decorative', 'boolean', 'Presentational only (no semantics).', 'true'),
    r('label', 'ReactNode', 'Text or node inside the pill when `variant` is `label`.', '—'),
    r('labelAlign', '"left" | "center" | "right"', 'Pill placement when `variant` is `label`.', 'center'),
    CN,
    MORE,
  ],
  'section-header': [
    r('SectionHeaderTitle', 'h2', 'Primary heading text.'),
    r('SectionHeaderDescription', 'p', 'Supporting summary copy.'),
    r('SectionHeaderActions', 'ReactNode', 'Trailing action area (buttons, toggles, links).'),
    CN,
    MORE,
  ],
  sheet: [
    r('open', 'boolean', 'Sheet visibility.'),
    r('onOpenChange', '(open: boolean) => void', 'Visibility callback.'),
    CN,
    MORE,
  ],
  sidebar: [
    r('SidebarProvider.defaultOpen', 'boolean', 'Initial desktop open state.', 'true'),
    r('SidebarProvider.open / onOpenChange', 'boolean / fn', 'Controlled open state.'),
    r('Sidebar.side', '"left" | "right"', 'Dock side.', 'left'),
    r('Sidebar.variant', 'string', 'sidebar | floating | inset', 'sidebar'),
    r('Sidebar.collapsible', 'string', 'offcanvas | icon | none', 'offcanvas'),
    r('useSidebar()', 'hook', 'state, openMobile, setOpen, toggleSidebar, isMobile'),
    CN,
    MORE,
  ],
  skeleton: [
    r('className', 'string', 'Width/height via Tailwind utilities.'),
    MORE,
  ],
  slider: [
    r('value / defaultValue', 'number[]', 'Thumb positions.'),
    r('onValueChange', '(value: number[]) => void', 'Live update while dragging.'),
    r('onValueCommit', '(value: number[]) => void', 'Commit on release.'),
    r('min / max / step', 'number', 'Range and step.', '0 / 100 / 1'),
    r('disabled', 'boolean', 'Non-interactive.', 'false'),
    r('orientation', '"horizontal" | "vertical"', 'Axis.', 'horizontal'),
    CN,
    MORE,
  ],
  sonner: [
    r('theme', '"light" | "dark" | "system"', 'Toast chrome theme.'),
    r('position', 'ToasterProps["position"]', 'Viewport anchor.'),
    r('richColors', 'boolean', 'Semantic toast colors.', 'false'),
    r('expand', 'boolean', 'Expand stack on hover.', 'false'),
    r('duration', 'number', 'Default auto-dismiss (ms).'),
    r('visibleToasts', 'number', 'Max visible toasts.'),
    MORE,
  ],
  spinner: [
    r('className', 'string', 'Size via e.g. size-4.'),
    MORE,
  ],
  statistics: [
    r('StatisticLabel', 'string | ReactNode', 'Metric label.'),
    r('StatisticValue', 'string | number | ReactNode', 'Primary value display.'),
    r('StatisticHint', 'ReactNode', 'Optional helper or trend text.'),
    CN,
    MORE,
  ],
  status: [
    r('variant', '"neutral" | "success" | "warning" | "error" | "info"', 'Semantic status color style.', 'neutral'),
    r('size', '"default" | "compact"', 'Default uses 14px type and an 8px dot; compact uses 12px type and a 6px dot.', 'default'),
    r('dot', 'boolean', 'Show/hide leading status indicator dot.', 'true'),
    CN,
    MORE,
  ],
  steps: [
    r('Step.state', '"upcoming" | "current" | "complete"', 'State used to style step marker and text.', 'upcoming'),
    r('StepMarker.index', 'number', 'Step number when state is not complete.'),
    r('StepTitle', 'ReactNode', 'Step heading content.'),
    r('StepDescription', 'ReactNode', 'Supporting step details.'),
    CN,
    MORE,
  ],
  switch: [
    r('size', '"default" | "sm"', 'Track height 28px (default) or 20px (sm).', 'default'),
    r('checked', 'boolean', 'Controlled on state.'),
    r('defaultChecked', 'boolean', 'Initial on state.'),
    r('onCheckedChange', '(checked: boolean) => void', 'Toggle callback.'),
    r('disabled', 'boolean', 'Non-interactive.', 'false'),
    r('required', 'boolean', 'Form validation.', 'false'),
    r('name', 'string', 'Form name.'),
    CN,
    MORE,
  ],
  table: [
    CN,
    r('children', 'ReactNode', 'TableHeader, TableBody, TableRow, TableCell, etc.'),
    MORE,
  ],
  tabs: [
    r('value / defaultValue', 'string', 'Active tab id.'),
    r('onValueChange', '(value: string) => void', 'Tab change.'),
    r('orientation', '"horizontal" | "vertical"', 'Tab list axis.', 'horizontal'),
    CN,
    MORE,
  ],
  text: [
    r('variant', '"body" | "heading" | "display"', 'Typography group from the UDS type scale.', 'body'),
    r(
      'size',
      'TextSize',
      'Step within the selected group. See `TEXT_BODY_SIZES`, `TEXT_HEADING_SIZES`, and `TEXT_DISPLAY_SIZES`. Defaults to 14 / 24 / 48.',
    ),
    r(
      'lineHeight',
      '"regular" | "tight" | "loose"',
      'Line-height preset from `--uds-type-*` typography tokens.',
      'regular',
    ),
    r('weight', '"regular" | "medium" | "semibold" | "bold"', 'UDS font weight token.', 'regular'),
    r(
      'appearance',
      'TextAppearance',
      'Optional semantic color from `--uds-text-*` tokens (`text-uds-text-*`). See `TEXT_APPEARANCES` export for the full list. When omitted, uses `text-foreground`.',
    ),
    r('as', '"p" | "span" | "div" | "strong" | "em" | "label"', 'Polymorphic root element.', 'p'),
    CN,
    MORE,
  ],
  textarea: [
    r('value / defaultValue', 'string', 'Text content.'),
    r('onChange', 'ChangeEventHandler', 'Change callback.'),
    r('placeholder', 'string', 'Hint text.'),
    r('disabled', 'boolean', 'Non-editable.', 'false'),
    r('readOnly', 'boolean', 'Read-only.', 'false'),
    r('rows', 'number', 'Visible rows.'),
    r('maxLength', 'number', 'Character limit.'),
    CN,
    MORE,
  ],
  'time-input': [
    r('type', '"time"', 'Preset to native time input type.', 'time'),
    r('autoComplete', 'string', 'Time entry autofill hint.', 'off'),
    CN,
    MORE,
  ],
  'time-step-input': [
    r('type', '"text"', 'Read-only text field that displays the selected time label.', 'text'),
    r('value / defaultValue', 'string', 'Selected time value in 24-hour `HH:mm` format (e.g. `13:30`).'),
    r('onValueChange', '(value: string) => void', 'Called when a time option is picked from the dropdown.'),
    r('stepMinutes', 'number', 'Minute interval used to generate the dropdown options.', '30'),
    r('startTime / endTime', 'string', 'Range bounds in 24-hour `HH:mm` format.', '"08:00" / "18:00"'),
    r('format12Hour', 'boolean', 'Displays dropdown labels as 12-hour times with AM/PM.', 'true'),
    CN,
    MORE,
  ],
  'token-input': [
    r('type', '"text"', 'Internal editor input type.', 'text'),
    r('tokens / defaultTokens', 'string[]', 'Controlled or initial token chip list.'),
    r('onTokensChange', '(tokens: string[]) => void', 'Called whenever tokens are added or removed.'),
    r('value / defaultValue', 'string', 'Controlled or initial draft text before it is committed into a token chip.'),
    r('maxTokens', 'number', 'Maximum number of tokens allowed.'),
    r('allowDuplicates', 'boolean', 'Allow duplicate token labels.', 'false'),
    r('separators', 'string[]', 'Keys that commit draft text into a token (e.g. Enter, comma).', '[",", "Enter"]'),
    r('autoComplete', 'string', 'Prevents browser autofill on secret/token fields.', 'off'),
    r('autoCapitalize', 'string', 'Prevents mobile capitalization changes.', 'none'),
    r('autoCorrect', 'string', 'Disables mobile auto-correction.', 'off'),
    r('spellCheck', 'boolean', 'Disables spell-check underlines on token strings.', 'false'),
    CN,
    MORE,
  ],
  toggle: [
    r('pressed / defaultPressed', 'boolean', 'Toggle pressed state.'),
    r('onPressedChange', '(pressed: boolean) => void', 'Press callback.'),
    r('disabled', 'boolean', 'Non-interactive.', 'false'),
    r('variant', 'string', 'default | outline', 'default'),
    r('size', 'string', 'default | sm | lg', 'default'),
    CN,
    MORE,
  ],
  'toggle-group': [
    r('type', '"single" | "multiple"', 'One or many selections.'),
    r('value / defaultValue', 'string | string[]', 'Selected value(s).'),
    r('onValueChange', '(value) => void', 'Selection change.'),
    r('variant', 'string', 'default | outline', 'default'),
    r('size', 'string', 'default | sm | lg', 'default'),
    r('spacing', 'number', 'Gap between items.'),
    CN,
    MORE,
  ],
  toolbar: [
    r('Toolbar', 'role="toolbar"', 'Root toolbar container for grouped actions.'),
    r('ToolbarGroup', 'ReactNode', 'Logical action/control grouping.'),
    r('ToolbarDivider', 'visual separator', 'Thin vertical divider between groups.'),
    CN,
    MORE,
  ],
  tooltip: [
    r('open / onOpenChange', 'boolean / fn', 'Tooltip visibility.'),
    r('delayDuration', 'number', 'Show delay (ms).'),
    r('disableHoverableContent', 'boolean', 'Pointer cannot enter content.', 'false'),
    CN,
    MORE,
  ],
  'url-input': [
    r('type', '"text"', 'Renders an Input Group-style URL field with a protocol addon and domain/path text input.', 'text'),
    r('protocol', 'string', 'Leading static prefix shown in the left addon.', '"https://"'),
    r('placeholder', 'string', 'Domain/path placeholder for the editable field.', '"example.com"'),
    r('inputSize', '"default" | "sm"', 'Shared size for the wrapper and inner URL field.', 'default'),
    r('inputMode', 'string', 'Hints URL keyboard layout on mobile devices.', 'url'),
    r('autoComplete', 'string', 'URL autofill hint.', 'url'),
    CN,
    MORE,
  ],
}

export function getShadcnComponentProps(slug: ShadcnUiSlug): PropDefinition[] {
  return SHADCN_COMPONENT_PROPS[slug]
}
