// Generated by scripts/sync-docs-version-snapshot.mjs for @chg-ds/unified-design-system v1.0.2.
import { HouseIcon, cn } from '@chg-ds/unified-design-system'
import type { ComponentProps } from 'react'
import { CATALOG_META } from '../../catalog-meta'
import { getShadcnComponentMeta } from '../../shadcn-component-meta'
import { getShadcnComponentProps } from '../../shadcn-component-props'
import { getShadcnExamples } from '../../shadcn-examples'
import {
  SHADCN_UI_SLUGS,
  formatShadcnComponentName,
  getShadcnDocsUrl,
} from '../../shadcn-ui-registry'
import { getCustomSections } from '../../sections/custom-sections'
import { createDocsVersionBundle } from '../create-bundle'

function WelcomeMenuIcon(props: ComponentProps<typeof HouseIcon>) {
  const { className, ...rest } = props
  return <HouseIcon {...rest} size={32} className={cn('shrink-0', className)} />
}

const bundle = createDocsVersionBundle({
  id: '1.0.2',
  catalog: CATALOG_META,
  shadcnSlugs: SHADCN_UI_SLUGS,
  getCustomSections,
  getShadcnComponentMeta,
  getShadcnComponentProps,
  getShadcnExamples,
  formatShadcnComponentName,
  getShadcnDocsUrl,
  welcomeMenuIcon: WelcomeMenuIcon,
})

export default bundle
