import React from "react"
import Icon from "./Icon"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Icon,
  "https://www.figma.com/file/LkIyThUA0oVNsDEAyOF7ER/Design-System--Components?node-id=1393%3A7018",
  {
    props: {
      icon: figma.instance("Icon"),
    },
    example: (props) => <Icon />,
  },
)
