// Generated by scripts/sync-docs-version-snapshot.mjs — do not edit manually.
import type { DocsVersionId, DocsVersionManifestEntry } from './types'

const CURRENT_DOCS_PACKAGE_VERSION = __DOCS_VERSION__ as DocsVersionId

export const DOCS_VERSION_MANIFEST = {
  defaultVersion: CURRENT_DOCS_PACKAGE_VERSION,
  versions: [
    {
      id: '1.0.5',
      label: `Documentation - v1.0.5`,
    },
    {
      id: '1.0.4',
      label: `Documentation - v1.0.4`,
    },
    {
      id: '1.0.3',
      label: `Documentation - v1.0.3`,
    },
    {
      id: '1.0.2',
      label: `Documentation - v1.0.2`,
    },
    {
      id: '1.0.1',
      label: `Documentation - v1.0.1`,
    },
  ] satisfies DocsVersionManifestEntry[],
}

export function getDocsVersionManifest() {
  return DOCS_VERSION_MANIFEST
}

export function getDocsVersionOptions(): DocsVersionManifestEntry[] {
  return DOCS_VERSION_MANIFEST.versions
}

/** Newest snapshot in the manifest (first entry, semver-desc). */
export function getLatestDocsVersionId(): DocsVersionId {
  return DOCS_VERSION_MANIFEST.versions[0]?.id ?? DOCS_VERSION_MANIFEST.defaultVersion
}
