// Generated by scripts/sync-docs-version-snapshot.mjs — do not edit manually.
import type { DocsVersionId, DocsVersionManifestEntry } from './types'

/** Installed package version this docs build documents (from package.json at build time). */
export const DOCS_PACKAGE_VERSION = __DOCS_VERSION__ as DocsVersionId

export const DOCS_VERSION_MANIFEST = {
  /** Frozen snapshot loaded by default (latest minor/major docs release, not every patch). */
  defaultVersion: '1.0.5' as DocsVersionId,
  versions: [
    {
      id: '1.0.5',
      label: `Documentation - v1.0.5`,
    },
  ] satisfies DocsVersionManifestEntry[],
}

export function getDocsVersionManifest() {
  return DOCS_VERSION_MANIFEST
}

export function getDocsVersionOptions(): DocsVersionManifestEntry[] {
  return DOCS_VERSION_MANIFEST.versions
}

/** Newest snapshot in the manifest (first entry, semver-desc). */
export function getLatestDocsVersionId(): DocsVersionId {
  return DOCS_VERSION_MANIFEST.versions[0]?.id ?? DOCS_VERSION_MANIFEST.defaultVersion
}

/** False until a second minor/major docs snapshot exists (hides sidebar version selector). */
export function shouldShowDocsVersionSelector(): boolean {
  return DOCS_VERSION_MANIFEST.versions.length >= 2
}
