// Generated by scripts/sync-docs-version-snapshot.mjs — do not edit manually.
import type { DocsVersionId, DocsVersionManifestEntry } from './types'

/** Installed package version this docs build documents (from package.json at build time). */
export const DOCS_PACKAGE_VERSION = __DOCS_VERSION__ as DocsVersionId

export const DOCS_VERSION_MANIFEST = {
  /** Frozen snapshot loaded by default (latest minor/major docs release, not every patch). */
  defaultVersion: '1.3.0' as DocsVersionId,
  versions: [
    {
      id: '1.3.0',
      label: `Documentation - v1.3.0`,
    },
  ] satisfies DocsVersionManifestEntry[],
}

export function getDocsVersionManifest() {
  return DOCS_VERSION_MANIFEST
}

export function getDocsVersionOptions(): DocsVersionManifestEntry[] {
  return DOCS_VERSION_MANIFEST.versions
}

/** Newest snapshot in the manifest (first entry, semver-desc). */
export function getLatestDocsVersionId(): DocsVersionId {
  return DOCS_VERSION_MANIFEST.versions[0]?.id ?? DOCS_VERSION_MANIFEST.defaultVersion
}

/** Version selector removed from the docs Menu; always false. */
export function shouldShowDocsVersionSelector(): boolean {
  return false
}
