// Generated by scripts/sync-docs-version-snapshot.mjs — do not edit manually.
import type { DocsVersionBundle, DocsVersionId } from './types'

export const docsVersionBundleLoaders: Record<
  DocsVersionId,
  () => Promise<{ default: DocsVersionBundle }>
> = {
  '1.0.5': () => import('./1.0.5'),
}
