// Generated by scripts/sync-docs-version-snapshot.mjs — do not edit manually.
import type { DocsVersionBundle, DocsVersionId } from './types'

export const docsVersionBundleLoaders: Record<
  DocsVersionId,
  () => Promise<{ default: DocsVersionBundle }>
> = {
  '1.4.0': () => import('./1.4.0'),
}
